- src/components/xpipeBodyWidget.tsx
- src/index.tsx
- src/kernel/panel.ts
**Description**
Terminate debugger when output panel is dispose
**Test**
1. Click 'Debug' 
2. Closing or disposing the output panel will terminate the debugger
Note: Disposing the output panel while **not** in debug mode('Run') will also terminate the debugger.
> Terminate debugger when output panel is dispose

- xai_components/xai_learning/tf_keras.py
This allows the user to specify the target shape of the image when reading it from the file. If none is specified, it will infer the shape from the model's input shape.
> Add target shape to KerasPredict Component

- src/xpipeWidget.tsx
When a user clicks on a File in Jupyter Lab and then wants to delete a node, it would result in Jupyter Lab also wanting to delete that particular file. 
With this change, a click on the xpipes editor will result in the focus being moved back to the editor, so the delete key will not trigger the delete command on the file browser.
> Force focus on the xpipes editor when a user clicks on it

- adr/0000-TEMPLATE.md
- adr/0001-Specify Components with Decorator.md
- src/components_xpipe/Sidebar.tsx
- tsconfig.tsbuildinfo
- xai_components/base.py
- xai_components/xai_learning/inference.py
- xai_components/xai_learning/tf_keras.py
- xai_components/xai_learning/training.py
- xai_components/xai_modelstash/modelstash_core.py
- xai_components/xai_pytorch/training.py
- xai_components/xai_spark/pyspark_core.py
- xai_components/xai_spark/pyspark_mllib.py
- xai_components/xai_template/example_components.py
- xpipes/handlers/components.py
This adds the ADR on using a decorator to specify what components should be available, and implements those changes.
1. Components List
1. Start Jupyter Lab
2. Switch to component list
3. Assert that all expected components are available
2. Specifying Component Colors (precondition: Jupyter Lab already running)
1. Switch to component list
2. Add / Change `color=` keyword on `@xai_component` decorator for the chosen component
3. Click reload to see border color change of component
> Use `@xai_component` to specify which components should be exposed in UI

- xpipes/handlers/compile.py
When jupyter lab is running with a `--notebook-dir` that is different from its starting directory, compiling a file will result in a `File not found` exception. 
This it uses a relative file path which is resolved relatively to the current working directory. 
This PR changes this behavior to make it resolve the path relative to the `server_root_dir`, which points to the absolute directory for the `--notebook-dir` (or `--ServerApp.root_dir`) parameter.
1. Ensure it solves the actual problem
1. Start jupyter lab with `--notebook-dir=examples`
2. Create new xpipes file
3. Add and connect HelloComponent
4. Save + Compile + Run it
5. See the output of the running script
2. Ensure it didn't break previously working behavior
* Follow the same steps as in previous test, but start without …
> Use absolute path when compiling an xpipes file

- xpipes/handlers/config.py
Due to the way wheels are installed, we need to use the config.ini inside the `xai_components` library.
1. Install xpipes from a wheel
1. Start jupyter lab
2. Check that component list is showing up
(Konsole)
> Use Config that comes in xai_components folder

- xpipes/handlers/components.py
As the component parser now looks into multiple directories, it is possible to have component duplication.
This solves the issue by only using the latest one it finds based on the header and component name.
1. Have duplicate components
1. Copy xai_components to examples folder
2. cd examples
3. jupyter lab
4. Check that only one set of components exists
5. Change HelloComponent in examples folder to have `color="green"`
6. Refresh component list and HelloComponent should be green now
> Deduplicate Components

- xpipes/start_xpipes.py
Was testing out the wheel creation process, was pleased to find that the Xpipes wheel build and usage is still robust in Windows, where the user simply needs to `pip install xpipes.whl` and run `xpipes`. `xpipes` will copy xai_components and .xpipes config to the current path, then launches jupyterlab.
In Linux running `xpipes` didn't work properly as the path was hardcoded to venv windows pathing. This pull request creates yet another hardcoded path handler for Linux.
https://github.com/XpressAI/xpipes/pull/63
**Build Wheel**
Referring to the previous pull request, you would need to run:
```
Install build
py -m pip install --upgrade build
Run this command from the same directory where pyproject.toml is located.
py -m build
This command should output a lot of text and once completed …
```
> Add linux handler for start_xpipes.py

- src/components/xpipeBodyWidget.tsx
- src/components_xpipe/Component.ts
- src/components_xpipe/Sidebar.tsx
- xpipes/handlers/components.py
The changes in https://github.com/XpressAI/xpipes/pull/72 allow multiple paths to be scanned for components. 
These paths don't have to be on the regular python path. 
The default components are on the python path by virtue of being installed. 
But custom components aren't forced to be there. A user might for example keep their custom components in their home directory, or in ther working directory, or in any number of other places. 
The changes in this PR introduce support for actually accessing components in abitrary places. 
1. Create new component and use it
1. Start jupyter lab
2. Create folder `xai_components/xai_example`
3. In that folder, create `example.py` with the content below.
4. Create new xpipes file
5. Add Both HelloWorldComponent and HelloComponent to the canvas and …
> Handle Components outside the python path

- src/components/xpipeBodyWidget.tsx
This fix the hyperparameter's code generator.
#80 
1. Can the xpipes run the `Hyperparameter` components?
1. Create new xpipes
2. Drag any `Hyperparameter` components and connect its to any component(e.g `HelloListTupleDict`).
3. Make sure it can run successfully.
2. Run any example but use `Hyperparameter` instead of `Literal`.
> 🐛Fix Hyperparameter components code generator

- examples/MSTrainUpload.xpipes
- src/components/xpipeBodyWidget.tsx
- xai_components/xai_learning/training.py
- xai_components/xai_modelstash/modelstash_core.py
The previous modelstash pull request #70 created components for local modelstash deployment. This pull request updates the library when in performing modelstash operations in Konsole (you do not need to specify a session user & password). 
I have also updated the `UploadToModelStash` component so that it uploads the model as a model version if say a base model has been created already. 
1. Basic Sanity Check
Run a simple `ListModel` component in local and inside Konsole. Don't forget if you're running it local you'll need to use the `StartLocalModelstashSession` component. 
2. Test UploadtoModelstash Component
I have updated the MSTrainUpload.xpipes example. Simply run it multiple times, and check in modelstash whether it properly logs the evaluation comparison. Try it in local and in …
> Update modelstash component library with Konsole handler + smarter UploadToModelStash 

- src/components/xircuitBodyWidget.tsx
- src/xircuitWidget.tsx
Fix Hyperparameter prompt does not appear when first running xircuits. 
1. Create and run xircuits which have hyperparameter components
1. Create a new xircuits
2. Make a simple working xircuits which include Hyperparameter
3. Close & open the xircuits
4. Run the opened xircuits
5. Is the hyperparameter prompt shown correctly?
2. Run any xircuits in `/examples` which have Hyperparameter components
1. Is the hyperparameter prompt shown correctly?
Still working on fixing initializing hyperparameter prompt when in `dirty` state.
> 🐛 Fix initialize hyperparameter when opening xircuits

- src/components/CustomNodeWidget.tsx
This will enable to edit literal node by double clicking it.
1. Double click any literal node to edit the value
> ✨Double click to edit literal node

- src/components/CustomNodeWidget.tsx
- src/components/xircuitBodyWidget.tsx
This will fix **ports type check** by reverting back to using `customDeserializeModel`
Caused by #75. Fix by reverting to #30 
1. Please check does all the port type checking works.
2. Please check does the dirty state still works.
> 🐛Fix ports type check

- src/components/xircuitBodyWidget.tsx
- xai_components/base.py
This will print "Finish Executing" at the end of every run process.
1. Run any xircuits
1. Does it print out the msg at the end of the run process?
> 🎨Add end msg after run process

- src/tray_library/Sidebar.tsx
- src/tray_library/TrayItemWidget.tsx
- xircuits/handlers/components.py
This fix **double clicking** and **ctrl-click** a component library to open its python script.
1. **Ctrl+click** any component in component_library to open its script.
2. Also, try **double clicking**.
> 🐛Fix path to open components script

- .github/workflows/build-python-wheel.yml
- package.json
- schema/plugin.json
- src/commands/ContextMenu.ts
- src/components/CustomNodeFactory.tsx
- src/components/CustomNodeWidget.tsx
- src/components/XircuitsApp.ts
- src/components/xircuitBodyWidget.tsx
- src/index.tsx
- src/log/LogPlugin.ts
- src/xircuitWidget.tsx
This added a context menu for xircuits by right-clicking it. 
Currently, the context menu have 6 options which are:
1. Edit
2. Delete
3. Save
4. Run Xircuits
5. Create New Xircuits
6. Open Xircuits Log Console
For `Edit` & `Delete`, it's only enable when right-clicking a node. However, `Edit` only works for **Literal Node**.
Also, fix literal node editing when cancel is pressed or no input provided.
1. Do test the 6 options in the context menu. All of these options are explanatory by their given name except for 1) & 2)
1. Edit: Enable to edit Literal Value
2. Delete: Enable to delete any node
2. Do check the previous function for edit and delete still works
1. Edit: Double clicking Literal Node
2. Delete: Press 'Delete' or 'backspace' keys on any node
3. While editing, either provide an …
> ✨Add context menu

- .github/workflows/build-python-wheel.yml
- src/debugger/SidebarDebugger.ts
- src/index.tsx
- src/kernel/panel.ts
- src/svg.d.ts
- src/ui-components/icons.tsx
- src/xircuitFactory.ts
- style/base.css
This will change some of the icons to use the [LabIcon](https://github.com/jupyterlab/jupyterlab/tree/3.1.x/packages/ui-components#labicon---set-up-and-render-icons), icon class used by JupyterLab.
The icons changed into `LabIcon` are :
1. xircuits
2. debugger
3. lock
4. breakpoint
This also replace the **refresh** icon to xircuits's icon
1. Make sure the changed icons are correct and render properly.
2. Try refreshing the jupyterlab. It should render a xircuits's icon rather than jupyterlab's with the same orbit's icon.
Currently, there some icons still need the css class to be style. Icons can be styled by passing CSS parameters into `.element(...`) as shown [here](https://github.com/jupyterlab/jupyterlab/tree/3.1.x/packages/ui-components#how-to-render-an-icon-into-a-dom-node) if needed …
> 💄Change into labIcon and replace the refresh icon

- src/index.tsx
- src/kernel/panel.ts
This will fix the 'zombie' kernel still exist when closing/refreshing tab.
Also, as discussed before, remove the need to create a kernel every time run button clicked. Currently, it'll use the same kernel as long as the output panel still exist.
#55 
1. Try running xircuits multiple times without closing the output panel. 
1. The xircuits shouldn't prompt user to select a kernel after the first run.
2. It'll only use the kernel created when the first run was clicked.
2. Try running xircuits and then remove the output panel.
1. Try run it again and it should prompt user to select a kernel.
3. While the output panel exist, close/reload the tab.
1. The xircuits's kernel shouldn't exist in the 'Running Kernels' panel.
**Don't manual close the xircuits's kernel in the 'Running Kernels' panel. …
> 🐛Fix kernel not dispose when closed

- src/kernel/panel.ts
This will fix the output panel broken when no kernel selected.
1. When running any xircuits, don't pick any kernel. 
1. Click Run again.
2. It should prompt to select a kernel. 
3. Select a kernel.
4. Xircuits should be able to run as usual.
> 🐛Dispose output panel when no kernel selected

- .github/workflows/build-python-wheel.yml
When downloading the github action artifacts, every file is named `xircuits-wheel`. For the sake of distinguishing which is which, I've added the branch name and the commit hash.
1. Check the artifact in this pull request. It should have the branch name and hash.
> updated wheel name in github action

- src/components/CustomPortModel.ts
This will skip `any` type check.
1. Open examples/KerasModelPredict.xircuits
2. Delete and Add new `KerasPredict` node
3. Connect  **`model`** from `ResNet50` into **`model`** in `KerasPredict`
4. You should be able to connect the link when doing the above.
5. Run the xircuits.
> 🐛Fix type check 'any'

- src/components/xircuitBodyWidget.tsx
- src/dialog/RunDialog.tsx
This will make the added arguments for spark submit use the previous input as default value.
1. Run xircuits using spark submit with added argument
2. Run again with spark submit and see if the previous input of added args is still there
> ✨Remember last input of added arguments for spark submit

- src/components/xircuitBodyWidget.tsx
This will only allow xircuits to compile when Run option is chosen.
1. Run xircuits with spark submit and see does it compile/update its python script. It shouldn't update it.
2. Also, run xircuits with the default (Run) option and see does it compile/update its python script. It should still update it.
> Don't compile when doing spark submit

- src/components/xircuitBodyWidget.tsx
This will create an optional code generator for the python compiler. Either default run or debugging.
1. Make sure xircuits is runnable.
1.Also, see its python script, does it have like `flask` etc.? It shouldn't have it.
2. Run xircuits with debugger and kill it. See its script. It should've all the necessary thing like `flask` etc.
1. Also, try run the xircuits using the '`run w/o compile`' option to run its script. It should be able to run.
> 🎨Create optional python compiler code generator

- examples/UtilsZipDirectory.xircuits
- xai_components/xai_utils/utils.py
During Spark Submit in cluster mode, users would need to bundle their python packages and xai_component library. This PR provides the `ZipDirectory` component which can do it in python. 
It is smart enough to create a new zip if `zip_fn` doesn't exist (if not provided, will use xircuits_name as fn), and add it to the zip if fn already exists. It is also has the option to include / exclude the root dir. 
For example if you'd like to zip your venv site packages you could zip it like:
```
venv.zip
└── site-packages
└── lib1
└── lib2
```
or you can zip it excluding site-packages:
```
venv.zip
└── lib1
└── lib2
```
I've also added a xircuits in the examples folder (since people would need to do it before spark submitting anyways) and for you to try.
You can either start from a new .xircuits or …
> 📖 xai lib utils zip component

- .gitignore
- xircuits/start_xircuits.py
Previous launch via `xircuits` in linux was hard coded. This PR makes it slightly smarter.
#85 
**1. Test Xircuits Start in Linux**
1. Create venv in Linux with any name you want
2. install xircuits
3. launch xircuits with `xircuits`
Add if any.
> 🐛 Fix Xircuits start in Linux

- src/commands/NodeActionCommands.ts
- src/components/xircuitBodyWidget.tsx
- src/context-menu/NodeActionsPanel.tsx
- src/context-menu/TrayItemPanel.tsx
- src/tray_library/Sidebar.tsx
- style/NodeActionPanel.css
This will enable to open the python script of node in canvas.
1. Drop any node via sidebar or component panel
2. Open context menu on the node (ctrl+left-click)
3. Select `Open Script`
4. It'll open its script
It's only works for any latest dropped node. Any old nodes that's already on canvas will not work as it doesn't have `file_path` data.
> ✨Add context menu option to open node's script

- src/components/XircuitsApp.ts
- src/components/xircuitBodyWidget.tsx
This just refactor `customDeserializeModel`.
1. Make sure the dirty state still usable by adding/removing nodes
> ♻️Refactor customDeserializeModel

- src/components/CustomPortModel.ts
This will allow literal for `any` type check
1. Change `any` in the python script. For example:
```
@xai_component
class HelloListTupleDict(Component):
input_list: InArg[any]
```
2. Try connecting any literal to that port. It should be able to link.
> 🐛Fix any type input doesn't accept literal

- requirements-full.txt
- requirements.txt
- xircuits/handlers/request_folder.py
- xircuits/start_xircuits.py
This PR improves the xircuits entry point by allowing users to pull `xai_components` from the base github repository. The old method assumed that users would use `venv` to install xircuits, which is fragile and will fail when installing on other venvs like conda. 
I've made it so that request_folder.py util is also very extendable, which can be used to pull other things users may need such as examples and their own component libraries.
#126
**1. Verify successful xai_component pull from repo**
1. Download the wheel from github action
2. Install it
3. start xircuits with `xircuits`, accept to download xai_components when prompted
4. Verify that `.xircuits` and `xai_components` exist
5. Verify that xircuits works as expected
There were multiple ways of copying xai_components to user dir …
> ✨ Pull components from repo

- src/components/XircuitsApp.ts
- src/components/link/CustomLinkFactory.tsx
- src/components/link/CustomLinkModel.ts
This will create custom links animation for triangle and non-triangle(custom) ports. 
Custom link
1. Unselected : Gray line
2. Selected : Yellow `stroke-dashoffset`
Triangle link
1. Unselected : Blue `stroke-dashoffset`
2. Selected : Yellow line
1. Try the 4 line conditions mentioned above.
2. Connect the links as usual and run xircuits.
> 🎨Create custom and triangle link animation

- setup.py
- xircuits/handlers/request_folder.py
- xircuits/start_xircuits.py
As we are now able to pull folders directly from the repo, adding a console command entry point for users to download examples is simple. With this PR, users can download the examples and datasets with `xircuits-examples`
#131 
**1. Test Download Examples & Datasets Feature**
1. Download the wheel from github action
2. Install it. You'd probably want to install [full], `pip install xircuits-1.2.0-py3-none-any.whl[full]`
3. Download the examples with command `xircuits-examples`
4. Verify that `examples` and `Datasets` were downloaded
5. Run with `xircuits` and verify that examples works as expected (KerasPredict.xircuits should be the fastest)
I've also changed the logic the tqdm progress bar from folders processed -> files downloaded in this PR.
> ✨ Add console command to download examples + datasets

- src/components/xircuitBodyWidget.tsx
- xai_components/xai_template/example_components.py
This add new component called `AddImport` that manually added a `string` import to the code generator script.
1. In template category, use the `AddImport` component.
2. Link a literal string to `import_str` port.
3. Compile.
4. Check the script and see does it add the `import_str`'s value to the import.
Only allow one `string` import per component.
> ✨Add component that enable to add import

- src/context-menu/ComponentsPanel.tsx
This fix scrolling through component panel and selecting a component but it scroll to top instead of adding the node.
Bug(Gif):
1. Open component panel(Right-click)
2. Open any category
3. Scroll through bottom and choose a component
4. It's expected to add the node instead of scroll back to top(Shown in Gif)
> 🐛Fix component panel auto-scroll back to top.

- adr/0002-Enable Data Passing via Context.md
- adr/0002-Refactor Component Libraries as Submodules.md
- adr/0003-Refactor Component Libraries as Submodules.md
- adr/0004-Define Component Libraries and Templates Implementation.md
- requirements.txt
- setup.py
- xircuits/handlers/request_folder.py
- xircuits/handlers/request_submodule.py
- xircuits/start_xircuits.py
This PR introduces more console commands which focuses on downloading component libraries. While dev users using the cloned repo can use `git submodule init` and `git submodule update` to pull the xai_components, users downloading from pip will not be able to as it is no longer a git repository. 
This PR introduces the `xircuits-components` command that allows users to download them.
**1. Check normal Xircuits component command**
1. Install the wheel from the github action
2. run `xircuits-components`. Verify that `xai_components` have been downloaded.
**2. Check Xircuits component command from a specific branch**
1. …
> ✨ Xircuits Entry Handler for Components + Submodule Components Download

- src/components/port/CustomPortModel.ts
This will allow link ports of same type.
1. Try connecting `outPort` of `string` type to `inPort` of `string` type
> 🐛Fix same type port cannot linked

- src/commands/NodeActionCommands.tsx
- src/components/xircuitBodyWidget.tsx
This will enable automatic link of `outPorts` when ▶ linked. If there exist any `outPort`, it'll automatically link that port into next node's `inPort` with similar name.
1. Easiest example is SparkSQLPlotBar.xircuits
1. Try linking ▶ to ▶ from e2e.
2. It's expected other `outPorts` will automatically link to `inPorts` with same name.
**Disclaimer**
This just a simple 'finding a similar name' kind of thing. It doesn't knows where it should connect. It'll not cover all use case.
> ⚡️Link obvious port

- src/components/xircuitBodyWidget.tsx
- src/xircuitFactory.ts
- ui-tests/tests/E2E.spec.ts
This update and rearrange the toolbar button. Also, switch the shortcut keys between context menu and component panel.
Removed:
1. Revert
Added:
1. Undo
2. Redo
3. Cut
4. Copy
5. Paste
1. Test each toolbar button 
2. Right-clicking canvas to open context menu
3. Ctrl+left-click to open component panel
> 🎨Update toolbar button and switch context menu shortcut key

- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
This will allow `outPort` of `any` type to link to any `inPorts` regardless of the `type`.
#111 
1. Open KerasModelPredict.xircuits.
2. Try to link ResNet50's `model` outPort to any port(except ▶) of KerasPredict.
3. It's expected to linked together.
> 🐛Skip any type check of outport

- xai_components/xai_pytorch/training.py
Welcome to Xircuits! Thank you for making a pull request. Please ensure that your pull request follows the template.
Fix typo in `xai_pytorch/training.py` PrepareUnetDataLoader component
None
**1. Test A**
1. Reload node on Xircuits
2. Save and compile
3. Run
Add if any.
> ✏️ typo fix for pycaret component library

- src/commands/NodeActionCommands.tsx
- src/context-menu/TrayItemPanel.tsx
- src/index.tsx
- src/tray_library/AdvanceComponentLib.tsx
- src/tray_library/Sidebar.tsx
- src/tray_library/TrayItemWidget.tsx
- xircuits/handlers/components.py
This PR will enable to open node's script and go to its specific line.
Ways to open script are via context menu and component library.
1. Drag a node to canvas.
1. Open context menu
2. Choose `Open Script`
3. It'll go to that node name 
2. (Additional) `Ctrl+click` or `double-click` any node on component library(sidebar).
1. It'll open its script and go to that node name 
Need to update JupyterLab to at least **3.4.0v**.
Notice a few bugs with this latest JupyterLab update. Probably need to check on that or fix the version.
> ⚡️Open node's script at specific line 

- src/commands/NodeActionCommands.tsx
- src/components/DragNewLinkState.ts
- src/components/xircuitBodyWidget.tsx
- src/context-menu/TrayItemPanel.tsx
This will fix adding node via component panel or dropped link. Previously, when updating the package-lock file, this feature cannot be use. It's due to incorrect node position and somehow the `sourcePort`'s data is missing(Not sure why).
#121 
1. With latest update of package-lock.json
1. Git clone new repo
2. Delete package-lock.son and tsconfig.tsbuildinfo
3. Install development as usual
4. Create xircuits file
5. Add node via component panel or dropped link
2. Try also from the wheel
Note: Haven't tested both but I assumed it'll work.
Currently, the comment component is broken. It doesn't show the comment's textarea. Haven't figured out what causing this.
Also, the context menu's position is kinda wrong.
> 🐛Fix adding node via link

- README.md
- package-lock.json
- src/commands/NodeActionCommands.tsx
- src/components/DragNewLinkState.ts
- src/components/xircuitBodyWidget.tsx
- src/context-menu/TrayItemPanel.tsx
- xircuits/handlers/components.py
We have identified that those two methods (str.removeprefix and ast.unparse) stop us from supporting python versions < 3.9. the current changes add support for python versions > 3.8. 
AST parsing differences between different Python versions:
- [Python 3.7](https://gist.github.com/mansouralawi/6dc729ec0e4ee946237eaa3019c7ad5c)
- [Python 3.8](https://gist.github.com/mansouralawi/e6e1a90e9e048f5beee7d3540df5c357)
- [Python 3.9](https://gist.github.com/mansouralawi/64250ae9c4dcfaef753adcfe4646c6b2)
*What is preventing Xircuits from running on Python 3.7 is the missing of `end_lineno` and `end_col_offset` from the AST parse.*
this PR is based on an older PR https://github.com/XpressAI/xircuits/pull/87 
- Manual test for same Xircuits behaviour and features as before:
1. Clone Xircuits
2. …
> ⚡️Compatibility with python 3.8 and above versions

- src/components/XircuitsApp.ts
- src/components/state/DragDiagramItemsState.ts
- src/components/state/MoveItemsState.ts
This will enable to save points created on any link with a listener to detect its changes. The listener also included when moving node.
1. Points created still exist when reopen xircuits
1. Open any example
2. Try add points on any link
3. Save
4. Close and reopen xircuits
5. Points created still exist
2. Listener when moving node
1. Make sure xircuits not in _'dirty'_ state
2. Try moving node and release mouse button
3. You will see xircuits is in _'dirty'_ state
3. Listener when creating point
1. Make sure xircuits not in _'dirty'_ state
2. Try adding point on any link created and release mouse button
3. You will see xircuits is in _'dirty'_ state
> ✨Able save points on link and add listener when moving node

- src/components/CustomNodeWidget.tsx
- src/dialog/CommentDialog.tsx
- style/Comment.css
This fix and improve the UI of comment component.
#150 
1. Does the content of the comment render?
1. Add comment node using context menu
2. Input some value and click 'Submit'
3. Comment node should be added into canvas with its input
> 🐛Fix comment component not rendering the content

- src/components/xircuitBodyWidget.tsx
- src/context-menu/ComponentsPanel.tsx
- style/ComponentsPanel.css
- style/NodeActionPanel.css
This will fix context menu and component panel from rendering at the wrong position.
1. Open context menu and component panel
1. Create `.xircuits` file
2. Right-click to open context menu anywhere on canvas
3. Drop a link onto canvas to open components panel
4. Make sure both panel was opened inside canvas 
5. Also, make sure it's spawn at the correct position where the mouse was clicked or link dropped
> 🐛Fix context menu and components panel spawn coordinates

- src/commands/NodeActionCommands.tsx
- src/components/state/MoveItemsState.ts
This will fix detecting node's position changes. It's also indirectly fix editing `Literal` node by double click as just selecting a node won't change the xircuits.
1. Just selecting node after moving a different node wont detect its changes.
1. Move a node
2. Save xircuits
3. Select a different node
4. See that xircuits is **not in `dirty` state**.
5. Repeat step 1-4 in a different branch. You will see that the xircuits in `dirty` state
2. Try double click any literal to edit it
> 🐛Fix node position changes

- src/components/CustomNodeWidget.tsx
- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
- style/ComponentInfo.css
This will fix the error tooltip to display the correct message. Next, I also change the error tooltip to use the markdown style for a richer text experience. In addition, all of the error messages have some changes to adapt with the new markdown style.
I added a `time.time` type symbol and default symbol which is to handle custom `types`.
1. Link incorrect type
1. Drag 2 component with outPorts
2. Connect a link with different type
3. Error tooltip should pop up 
2. Check all updated messages. Does it make sense?
3. See default port type
1. Drag a component with a specific/custom `type` (e.g CreateUnetModel)
2. You should see its port type symbol [`◎`](https://en.wikipedia.org/wiki/%E2%97%8E)
4. See `time.time` port type
1. Add a TimerComponent from branch fahreza/update-desc
2. You …
> 🎨Update port error tooltip to display expected type. Add timer and default port type symbols.

- src/components/xircuitBodyWidget.tsx
This will fix menu spawn position regardless which left sidebar is open.
1. Open context menu regardless which left sidebar is currently open.
2. It should spawn in the correct position
> 🐛Update spawn point when component panel is open

- src/components/CustomNodeWidget.tsx
- style/ComponentInfo.css
This will prevents propagation of the wheel event of canvas from being called.
This will fix #182 
1. Open node's description
2. Try to use mouse wheel to scroll
3. The canvas will not scroll
> 🐛Disable canvas scrolled when scrolling description tooltip

- src/commands/NodeActionCommands.tsx
This will allow multiple nodes to be deleted at the same time.
1. Select multiple nodes
2. Press `delete` or `backspace`
3. All of the nodes will be deleted at the same time except `Start` and `Finish` node
> 🐛Fix delete multiple nodes at the same time

- xircuits/handlers/request_folder.py
- xircuits/start_xircuits.py
This PR allows users to launch xircuits with any jupyterlab launch configs, ie instead of `jupyter lab --ContentsManager.allow_hidden=True` you can run `xircuits --ContentsManager.allow_hidden=True` 
Especially useful when in need to configure the spark remote run options.
https://github.com/XpressAI/xircuits/pull/164
**1. Enable show hidden files**
1. Launch Xircuits with
```
xircuits --ContentsManager.allow_hidden=True
```
2. In the`View` panel, click `Show Hidden Files`. You should be able to see the `.xircuits` directory.
You can try other jupyter launch options that you know.
Add if any.
> ✨ Wrapper for Jupyter Launch Args

- src/dialog/LiteralInputDialog.tsx
- src/dialog/RunDialog.tsx
- src/tray_library/GeneralComponentLib.tsx
This will fix run dialog for hyperparameter node. Also, fix the width of `integer` and `float` input.
1. Add any hyperparameter node.
2. Please input the prompted dialog.
3. Connect to any node with the correct type.
4. Save and click run
5. The dialog prompt should display what you define at step (2) and show its type
6. Make sure the hyperparameter node is able to use properly by clicking `Run` in the dialog.
> 🐛Fix hyperparameter dialog handling

- src/components/port/CustomPortLabel.tsx
This will truncated any long text. Max characters per line is 80.
1. Add Literal String
2. Insert a long one-line string (more than 80 characters)
3. You will see it'll not overflow 
4. Also, it'll render an ellipsis ("...") to represent the clipped text.
> 🐛Truncate long strings

- src/components/XircuitsApp.ts
- src/components/xircuitBodyWidget.tsx
This will allow links to be successfully render for the others unopened xircuits tabs every time refreshed/reloaded.
**Note: There might be some delay when rendering points on link**. Clicking on canvas should properly render it.
**Actual Issue**:
**Expected Fix**:
1. Open multiple xircuits. Make sure all are properly linked.
2. Refresh browser
3. Every xircuits tabs should still be properly linked. 
4. Expect a delay when rendering the points. Clicking on canvas should fix it.
5. Do steps 1-3 for the main branch. You should get the same as the gif in the **Actual Issue** above.
There might be some delay when rendering points on link. Clicking on canvas should properly render it.
> 🐛Fix links not rendering for unopened xircuits tab

- examples/KerasModelPredict.xircuits
- examples/KerasTrainImageClassifier.xircuits
- examples/SparkLinePlot.xircuits
- examples/SparkLogisticRegressionSample.xircuits
- examples/SparkPackageVenv.xircuits
- examples/SparkSQLPlotBar.xircuits
- examples/UtilsZipDirectory.xircuits
Earlier Xircuits workflows has an extra port for the Start and Finish nodes. This PR removes them. The updated workflows are:
- KerasModelPredict
- KerasTrainImageClassifier
- SparkLinePlot
- SparkLogisticRegression
- SparkPackageVenv
- SparkSQLPlotBar
- UtilsZipDirectory
1. Clone the repo, checkout to `fahreza/fix-original-ports`, install xircuits
2. Verify that the above examples does not have extra ports.
3. Verify that you are able to compile and run it. You don't have to run all of them.
Add if any.
> 🐛 Fix Extra Ports for Start and Finish Nodes

- src/components/xircuitBodyWidget.tsx
- src/dialog/LiteralInputDialog.tsx
- src/tray_library/GeneralComponentLib.tsx
This will automatically connect to its literal node when link is dropped from a parameter `InPort`. There are 2 type of implementation:
1. `Non-any` type - Drag a link should automatically render the correct literal node.
2. `any` type - The literal node's type is render based on the **first character of the given input**.
Types taken into consideration for `any` type are :
1. 1 - Int
2. . - Float
4. " - String
5. [ - List
6. ( - Tuple
7. { - dict
8. !true / !True/ !1/ !t - True
9. !false / !False / !0 / !nil - False
1. Drag link from `non-any` type `InPorts`
1. Drag a node which have `inPorts` with `non-any` type
4. Dropped a link from the port
5. A input dialog should popup based on its type
6. Insert any input and submit it
7. That port should be connected to its literal node 
2. Drag …
> ✨Directly connect parameter inPort to its literal node

- src/commands/NodeActionCommands.tsx
- src/components/xircuitBodyWidget.tsx
- src/dialog/LiteralInputDialog.tsx
- src/dialog/RunDialog.tsx
- src/tray_library/GeneralComponentLib.tsx
- xircuits/handlers/components.py
This PR is to update the general components' layout and naming
1. Load general components (Arguments, Literal)
2. Check components' color match with schema 
3. Check hyperparameter naming is changed to Argument 
color schema:
- Str: Pink
- Int: Blue
- Float: Green
- Bool: Red
- List: Yellow
- Tuple: Purple
- Dict: Orange
> Update General Component

- xircuits/compiler/compiler.py
- xircuits/compiler/parser.py
- xircuits/handlers/compile_xircuits.py
Currently the new compiler does not compile any xircuits canvas that has compulsory inPorts which is indicated as [★]. As currently Xircuits bakes the ★ into the label, it breaks the compiler due to ★ being a a special character. 
This PR updates the compiler to read .xircuits files using utf-8 encoding, then filters ★ from port strings.
https://github.com/XpressAI/xircuits/pull/209
https://github.com/XpressAI/xircuits/issues/210
Take the wheel and try compiling `examples/KerasTrainImageClassifier.xircuits`. It should correctly compile.
In the future we should rethink baking the ★ in the label.
> 🐛 Fix compulsory inPort args in new compiler

- src/components/xircuitBodyWidget.tsx
This PR fixes the bug that happens when a user presses compile and run without saving. The dialog will offer to save the canvas, but it is not saved by the time it is parsed by the compiler, and therefore will incorrectly run the previous state of the workflow.
To reproduce:
1. Create a new xircuits file
2.  Complete a workflow
3. Without pressing save -> compile, run Xircuits file.
Previously:
A python file will be generated, but it will be empty.
With this PR:
The compilation will perform correctly. 
1. Create a new xircuits file
2.  Complete a workflow
3. Without pressing save -> compile, run Xircuits file. 
Verify that the compilation is performed correctly.
> 🐛 Fix Save and compile run from not compiling correctly

- xai_components/base.py
- xai_components/xai_controlflow/branches.py
- xai_components/xai_pytorch/quickstart.py
- xai_components/xai_pytorch/torch_nn_layers.py
- xai_components/xai_spark/pyspark_core.py
- xai_components/xai_spark/pyspark_mllib.py
- xai_components/xai_template/example_components.py
- xai_components/xai_tensorflow_keras/keras_transfer_learning.py
- xai_components/xai_tensorflow_keras/tf_keras.py
- xai_components/xai_tensorflow_keras/training.py
- xai_components/xai_utils/utils.py
Only need __init__ functions when you want to specify a default value.
One of the more annoying things when creating a component is having to type InArg/OutArg over and over.  With this change we use `__annotations__` to get what args are defined on the component and automatically initialize those to In/OutArg.empty().
With this change you no longer need to implement `__init__` when creating components unless you want to give your args default values.
Example:
```
def __init__(self):
super().__init__()
self.learning_rate.value = 1e-3
self.should_flatten.value = False
```
Converted the branch and pytorch components to use the new `__init__`-less style.  Able to compile and run with no issues.
#N
> Make initializing In/OutArgs automatic.

- src/index.tsx
- xircuits/handlers/compile_xircuits.py
If there is an unexpected bug in the new compiler, a normal user has no idea what would cause it. A file will be created but it will be empty. This PR suggests a way to notify users.
Currently in 1.7 https://github.com/XpressAI/xircuits/commit/435f8709519a2e766b7da4ed82cc58ba5f1e15af there is a compile error when handling `Literal Dicts`. You can connect the `HelloListTupleDict` component to reproduce the error.
At compile, you should see an alert. Opening console log will give you a hint of what caused it.
> 🔔 Compile Fail Handler 

- xircuits/compiler/generator.py
Currently the new compiler crashes if a `Literal Dict` is used in a workflow, while compiling `Literal List` as tuples. This PR fixes both. 
Try compiling a workflow with both `Literal List` and / or `Literal Dict`. You can use the HelloTupleListDict component in the template library. It should compile correctly.
If possible try out https://github.com/XpressAI/xircuits/pull/224 before merging this one. Thanks.
> 🐛 Fix Literal List and Dict compile

- src/xircuitFactory.ts
Re-arrange the main Toolbar, move the save icon closer to the compile and run icons 
**1. Test A**
1. Build Xircuits
2. Check and test the new toolbar arrangement 
3. save, compile, run and Xircuits template 
Add if any.
> 💾  Re-arrange the main Toolbar

- src/components/port/CustomPortLabel.tsx
Updates long string display to overflow. Currently the limit is set to be 40ch. 
For reference, this is how it looks currently, for 40ch and for 80ch.
Previous:
40ch
80ch
https://github.com/XpressAI/xircuits/pull/190
1. Drag in a string component. Give it a long text, maybe from [here](https://www.lipsum.com/). Rate the aesthetic quality.
2. Run the workflow. Ensure that it can perform its function correctly.
> Update Long String Overflow Display

- src/components/port/CustomPortLabel.tsx
Align in triangles to the left and right triangles to the right.
See screenshot.
> Align the text for Triangle ports.

- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
- src/tray_library/AdvanceComponentLib.tsx
- xai_components/xai_multiple_types_test/multiple_types_test.py
Hello! 
I am part of the TVB team that has been using the Xircuits extension for a while to develop our own JupyterLab extension (see [tvb-ext-xircuits](https://github.com/the-virtual-brain/tvb-ext-xircuits))
As part of our development process, we found that we needed to have input ports that support more than just one input type (for example floats _and_ ints). So, we implemented this feature and wanted to ask if you would find it appropriate to merge this feature in your original code base.
On the React side we worked mostly on the validation part, when trying to link a Literal to an input port.
On the Python side there was no modification, but if you want to use this feature you should specify in your component's code that an input argument accepts multiple types. You should do it like …
> Make input ports support multiple input types

- src/tray_library/AdvanceComponentLib.tsx
Triangle components don't have a type like normal ports.  Add a check to skip the new logic if the port is a triangle.
> Fix for multi-triangle components.

- src/components/xircuitBodyWidget.tsx
Fix action panel spawn location after it spawn very far when on the right side of the canvas
Try to spawn the Action Panel (right-click) all over the canvas, it should spawn at the right place. 
Add if any.
> 🐛 Fix Action Panel Spawn Location

- xai_components/base.py
- xai_components/xai_controlflow/branches.py
- xai_components/xai_pytorch/quickstart.py
- xai_components/xai_spark/pyspark_core.py
- xai_components/xai_spark/pyspark_mllib.py
- xai_components/xai_template/example_components.py
- xai_components/xai_tensorflow_keras/keras_transfer_learning.py
- xai_components/xai_tensorflow_keras/tf_keras.py
- xai_components/xai_tensorflow_keras/training.py
- xai_components/xai_utils/utils.py
- xircuits/compiler/generator.py
This PR cleans the self.done which was a part of the old debugger.
https://github.com/XpressAI/xircuits/pull/237
Run any workflows. It should work as expected. If possible run the branch workflow components as well.
> 🧹 Remove unused debugger code from component libraries

- src/index.tsx
- src/kernel/panel.ts
- src/log/LogPlugin.ts
People with wide monitors have requested this update. I guess it makes sense for the output panel to spawn on the right side so it doesn't occupy 50% of the screen.
This PR also updates the output panel so it auto-scrolls to the bottom with each output. 
0. ~~Buy wide monitor~~
1. Grab the wheel for this PR
2. Install it and run any workflows
3. Verify it looks better
1. Run a Xircuits workflow with a lot of outputs, eg ControlflowLoop.xircuits.
2. Verify that the output panel auto-scrolls with the new outputs
> ⚡ make output panel auto-scroll and spawn on the right

- src/commands/NodeActionCommands.tsx
- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
- src/dialog/LiteralInputDialog.tsx
- src/helpers/InputSanitizer.tsx
- src/tray_library/GeneralComponentLib.tsx
- xircuits/compiler/generator.py
- xircuits/handlers/components.py
This pull request introduces the new `Literal Secret` component which users to input secret values such as passwords and API keys. The entered secrets are masked in the input dialogue and the canvas. Useful when demoing Xircuits while streaming.
Warning: Literal Secrets are masked in the frontend only. They can still be accessed in the raw .xircuits file or appear as strings in the compiled script.
1. drag in a Literal Secret component - confirm that the input dialogue for Secrets appear. Whatever is inserted in here is masked in dots.
2. confirm that on render, the canvas will only display ***** regardless of length
3. confirm that the Literal Secret component can be used normally as an input with other components such as print.
> 🗝️ Add Literal Secret Component

- src/components/link/CustomLinkFactory.tsx
The current canvas renders link animation in 60 fps, which builds up the resource consumption if you have lots of those. This PR limits it to 24 fps.
Before:
16.6ms for every new frame
Now:
30ms ~ 50 ms 
https://github.com/XpressAI/xircuits/pull/134
Test the resource consumption before and after using this PR's wheel.
> 🔗 Reduce Resource Consumption for Link Animation

- src/commands/CustomActionEvent.tsx
- src/commands/NodeActionCommands.tsx
- src/components/XircuitsApp.ts
- src/components/link/CustomLinkFactory.tsx
- src/components/link/CustomLinkModel.ts
- src/xircuitWidget.tsx
- xircuits/compiler/generator.py
This PR fixes bugs and enhances the cut-copy-pasting related functions and refines the event handling process. Specifically:
1. Prevent keyboard events from being fired multiple times when having multiple canvas tabs.
2. Enabled spawning on mouse coordinates. 
3. Enabled cross-canvas paste. 
4. Enabled cut-copy-pasting from the keyboard shortcuts.
5. Enabled links and link points for cut-copy-pasting.
6. Updated clone action from happening during the copy process.
https://github.com/XpressAI/xircuits/pull/105
https://github.com/XpressAI/xircuits/issues/184
**1. Test for Spawning on Mouse Coordinates**
1. Cut / copy a component
2. Right click on a canvas area and paste spawn
3. Ensure that the new component appears around at the mouse coordinates.
**2. Test for Cut-Copy-Pasting from the …
> ✨ 🐛 Enhancing Copy-Paste Functionality and Keyboard Events

- setup.py
- xircuits/handlers/request_folder.py
- xircuits/handlers/request_submodule.py
- xircuits/start_xircuits.py
This PR updates the default way `xircuits-components` fetches the components from pulling each file recursively to simply copying it from the site-packages (this behavior already exists if you run `xircuits` without xai_components present in your working dir, but it now the default for `xircuits-components` as well). 
If users would still want to fetch the components online or from a specific online branch, they can add the `--download` tag. This PR also updates several error messages in this process.
https://github.com/XpressAI/xircuits/pull/152
Install Xircuits from this PR's wheel and verify that:
1. when you run `xircuits-components`, it copies it from site-packages.
2. when you run `xircuits-components --download` it will download the components from an online source. Verify also …
> 🐛 Update xircuits-components to fetch from local

- src/commands/CustomActionEvent.tsx
This patch addresses an issue of event propagation between different active widgets (such as an input dialogue panel or the tray widget) in the Xircuits application. Previously, keyboard shortcuts (ctrl+z, ctrl+y, ctrl+s, ctrl+x, ctrl+c, ctrl+v, Delete, and Backspace) were executed regardless of the active widget, which resulted in unintended consequences.
The change ensures that the shortcuts are only executed when the event's target is within the currently active widget. This is achieved by adding a condition to check if the target of the event is contained within the active widget before executing any commands.
https://github.com/XpressAI/xircuits/pull/253
1. Copy a node. Then open an active panel (such as the tray widget or a string input dialogue panel).
2. Verify that on paste, it …
> 🐛 Stop event propagating between different active widgets

- xircuits/start_xircuits.py
This patch fixes a bug that was causing the installation of submodule libraries to fail on Linux systems in the xircuits project. The issue was due to the usage of the os.system function with a command that is specific to Windows. The code has now been refactored to use the subprocess.run function instead and directly calls pip as a module using the current Python executable. This approach is more reliable and portable across different Python environments and operating systems. 
https://github.com/XpressAI/xircuits/pull/226
1. Run `xircuits-submodules component-lib-name` on a Linux based system. Verify that the component is pulled and installed.
> 🐛 Fix Linux-based submodule install

- src/commands/NodeActionCommands.tsx
- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
- src/components/xircuitBodyWidget.tsx
- src/dialog/LiteralInputDialog.tsx
- src/dialog/formDialogwidget.tsx
- src/dialog/input-dialogues/ArgumentInput.tsx
- src/dialog/input-dialogues/BooleanInput.tsx
- src/dialog/input-dialogues/ChatInput.tsx
- src/dialog/input-dialogues/DictInput.tsx
- src/dialog/input-dialogues/ListInput.tsx
- src/dialog/input-dialogues/NumberInput.tsx
- src/dialog/input-dialogues/ParameterInput.tsx
- src/dialog/input-dialogues/SecretInput.tsx
- src/dialog/input-dialogues/StringInput.tsx
- src/dialog/input-dialogues/TextAreaInput.tsx
- src/dialog/input-dialogues/TupleInput.tsx
- src/dialog/input-dialogues/VariableInput.tsx
- src/helpers/InputSanitizer.tsx
- src/tray_library/GeneralComponentLib.tsx
- xircuits/compiler/generator.py
- xircuits/handlers/components.py
This PR implements a `Literal Chat` interface for Chat-like messages. Specifically, it allows users to specify [messages](https://platform.openai.com/docs/api-reference/chat/create) in an list of dicts. 
This PR also refactors form interfaces so that each Literal has its own customizable display, as well as fixes a Literal Tuple bug. 
**1. Try Literal Chat**
1. Drag a Literal Chat from the tray. 
2. Confirm that it you can correctly render the role and content.
3. Confirm that you can edit it and it preserves the previous state.
4. Confirm that it prints out a list of dicts as expected.
**2. Try Literal Tuple**
1. Drag a Literal Tuple. Confirm that you can edit and compile it.
**3. Try Literals and Arguments**
1. The literals and tuples have been refactored. Try dragging them, editing …
> ✨ Literal Chat

- src/commands/NodeActionCommands.tsx
- src/components/xircuitBodyWidget.tsx
- src/dialog/LiteralInputDialog.tsx
- src/dialog/input-dialogues/BooleanInput.tsx
- src/dialog/input-dialogues/NumberInput.tsx
- src/dialog/input-dialogues/VariableInput.tsx
- src/helpers/InputSanitizer.tsx
- src/tray_library/GeneralComponentLib.tsx
- xai_components/base.py
- xai_components/xai_template/example_components.py
This PR enables users to toggle Literal Booleans. Internally `Literal True` and `Literal False` are consolidated into `Literal Boolean`. The Boolean update is fully backwards compatible with older canvases.
Aside from that, this PR also:
- Refactored general components.
- Standardized literal type caps.
- Fixed Literal True / False from not rendering from an `any` port.
- Added the `chat` data type into base.py.
**1. Test Boolean Toggle**
- Drag in a `Literal True` or `Literal False`. Verify that a `Literal Boolean` with the respective `True` or `False` value is spawned.  
- Double click on it to spawn the edit menu form. Verify that the form spawns and it saved the old state (ie if it was a `Literal True` the form will show the `on` toggle.)
- Change the value. Verify that the new value …
> ✨/♻️ Enable Literal Bool Toggle + Refactor General Component Handling

- .github/workflows/run-ui-tests.yml
- .gitignore
- .gitmodules
- ui-tests/README.md
- ui-tests/e2e/datatype-test.spec.ts
- ui-tests/e2e/expected_outputs/01_datatypes.ts
- ui-tests/playwright.config.ts
- ui-tests/xircuits_test_utils.tsx
This PR adds a playwright test for Xircuits data types. It tests node connections for `String`, `Integer`, `Float`, `List`, `Tuple`, `Dict`, `Secret`, `Boolean`, as well as `Chat`, then performs tests on editing their values. It is updated to now test with 2 browsers, chrome, firefox.
This PR also introduces the groundwork for Xircuits - Playwright interface. Currently it supports:
- navigating through Jupyterlab directories
- compiling and running Xircuits
- connecting Nodes
- updating Literal values
- opening the jupyter xterm which basically enables any cmd commands.
I've also added a special component library for testing purposes [here](https://github.com/XpressAI/xai-tests). 
Finally, the github action now provides a playwright report to check the automation results. It is set to …
> 🤖 Datatype Automation Tests + Xircuits - Playwright Interface Library

- src/index.tsx
- src/log/LogPlugin.ts
- xircuits/.xircuits/config.ini
- xircuits/handlers/__init__.py
- xircuits/handlers/config.py
This PR allows users to specify the output panel and log panel spawn location via `config.ini`. 
https://github.com/XpressAI/xircuits/pull/241
**Test Update Output Panel Spawn Location**
1. Run Xircuits and run a workflow. Verify that the output panel spawns at the bottom (default location)
2. Navigate to `.xircuits/config.ini`
3. Update the `splitMode. Options are split-bottom, split-top, split-right, split-left.
4. Rrerun another workflow. Verify that the new spawn location is what have been specified.
> ✨ Enable Output Panel Spawn Location Through Config

- src/dialog/FormDialog.tsx
- src/dialog/input-dialogues/TextAreaInput.tsx
- src/helpers/InputSanitizer.tsx
- src/tray_library/GeneralComponentLib.tsx
This PR:
- bugfix: add handler if users submit empty parameter value
- bugfix: allow neg number parameters, add int / float typechecks
- bugfix: handle empty string validation
- enable autofocus on text string input
1. Drag in any literal component. Do not enter anything and press submit. Verify that an error message spawns and you can correct it.
2. Drag in an Int / Float. Verify that you can enter 0s and negative values. Also verify that each will correctly type check (ie entering 1.5 in integers will throw out an error message)
3. Drag in a Literal String. Verify that it doesn't explode and an error message spawns on empty content. 
4. Also verify that spawning the Literal String will autofocus on the text area, and on edit Literal String will focus on the end of the string.
> 🐛 Fix Various Literal Parameter Input Handling

- .github/workflows/run-ui-tests.yml
- setup.py
- xircuits/compiler/compiler.py
- xircuits/handlers/request_folder.py
- xircuits/handlers/request_submodule.py
- xircuits/start_xircuits.py
This PR revamps the Xircuits CLI. 
- Start Xircuits
- You may also append any [Jupyterlab launch commands](https://nocomplexity.com/documents/jupyterlab/notebooks/jupyterlab-cli.html), eg `xircuits start --no-browser`
- Fetches and pip installs a component library for Xircuits based on their requirements.txt.
- You may provide a component library name listed in the [component library list](https://github.com/XpressAI/xircuits/tree/master/xai_components), or provide a github repository url.
- Fetches and but does not install a component library for Xircuits.
- You may provide a component library name listed in the [component library list](https://github.com/XpressAI/xircuits/tree/master/xai_components), or provide a github repository url.
- Will return an error if the directory already …
> ✨ Revamp Xircuits CLI

- src/commands/NodeActionCommands.tsx
This PR fixes the following bugs:
- Fix open component script from canvas introduced in the upgrade to jupyterlab 4.
- Fix opening component script from tray when a canvas is not active
- Fix open script from not auto-centering
1. Open a workflow canvas, drag in a component and open script from the context menu. 
2. Open the component library tray sidebar, and double click to open script. 
For both steps, ensure that the component script opens and is centered.
> 🐛 Fix Open Component Script Features

- xai_components/xai_utils/utils.py
This pull request adds the `ExecuteNotebook` component to the Xircuits Component Library. The component is designed to automate the execution of Jupyter notebooks. It reads a notebook file, executes all cells in order, and can log the output to a file. 
**1. Test 1**
1. Loaded a simple data analysis notebook.
2. Executed the `ExecuteNotebook` component.
3. Verified the output and log file.
> 🧩 Execute Jupyter Notebook Component

- src/context-menu/CanvasContextMenu.tsx
- src/tray_library/Sidebar.tsx
- xai_components/xai_controlflow/library-config.ini
- xai_components/xai_pytorch/library-config.ini
- xai_components/xai_sklearn/library-config.ini
- xai_components/xai_spark/library-config.ini
- xai_components/xai_template/library-config.ini
- xai_components/xai_tensorflow_keras/library-config.ini
- xai_components/xai_utils/library-config.ini
- xai_components/xai_xgboost/library-config.ini
- xircuits/handlers/request_library.py
- xircuits/library/__init__.py
- xircuits/library/install_fetch_library.py
This pull request focuses has been on enabling users to set their own component library configurations. Specifically, they can add a `library-config.ini` and specify library-specific paths like `readme_path`, `default_example_path`, and `requirements_path` that will be loaded by the tray context menu. Configs for all the current internal XAI components (`xai_controlflow`, `xai_pytorch`, etc.) have been added in this PR.
This PR also fixes the spawn logic of several canvas context menu options.
https://github.com/XpressAI/xircuits/pull/281
1. Run the right click commands options on the tray context menu. Verify they work. 
2. Change the example paths in one of the library config. Run the context menu again. Verify that the updates are applied correctly.
1. Right click a component node, a …
> ✨ Allow Users to Set Component Library Configurations

- pyproject.toml
- xircuits/handlers/components.py
If someone has mac resource files around (usually starting with `._`), the parsing of components crashes. 
As we don't support hidden files as python files anyway, this change introduces a filter to skip any file that starts with `.`.
- None
**1. Reproduction Test**
1. Create a file called `._foo.py` in a component directory and make it a invalid python file, ideally with some random binary data
2. Without Change: Notice that component list can't be loaded anymore
3. With Change: Notice things continue to work
> Ignore hidden files when parsing for components

- package.json
- src/components/link/CustomLinkFactory.tsx
- src/components/node/CustomNodeWidget.tsx
- src/components/port/CustomPortLabel.tsx
- src/helpers/XircuitsCanvasWidget.tsx
- yarn.lock
This PR changes the rendering of Nodes and Links to make it look more modern. 
By making nodes a little transparent, it is now possible to see when links go behind them, and when links cross it is also easier to see where they are going.
By removing the empty landing ports, the graph can now also be a bit more compact.
It does require the user to click on "refresh all nodes" once, because react-diagrams won't re-route the links otherwise.
> Node Graph Rendering Facelift

- src/index.tsx
After the Jupyter Lab 4 migration, we've noticed that on slower machines sometimes the creation of a new Xircuits file resulted in a 0 byte file instead of creating a minimal xircuits diagram. 
The reason was that the context promise now resolves before the diagram is initially rendered. 
By awaiting the rendering of the diagram we ensure that the model is properly populated before we save it.
**1. Reproduction**
1. In developer tools set CPU performance to 6x slowdown
2. Create a new Xircuits file
3. Before the fix: In most cases (~80%) it can be observed that the created file has 0 bytes
4. After the fix: The created file always has more than 0 bytes
> Await rendering of Xircuits diagram before saving

- src/context-menu/ComponentsPanel.tsx
- src/tray_library/AdvanceComponentLib.tsx
- src/tray_library/Component.tsx
- src/tray_library/Sidebar.tsx
On larger workflow canvas with a very large component library collection, the call to `fetchNodeByName` is a very expensive operation as it performs a server call to refresh and fetch the latest node information. This function is used in reloading nodes, or creating literals from component library nodes.
This PR caches the component list and only triggers it at the beginning or when the component tray refresh button is pressed.
**1. Test Component Library Cache**
1. Open the console on Xircuits launch. Confirm that it logs that Xircuits is fetching the component library, and it completes.
2. Perform reload node, or create a literal from a component library. Confirm from the network tab that it does not fetch from the server.
3. Press the refresh button from the tray. Confirm that it …
> ✨ / 🐛 Cache Fetch Component List

- src/context-menu/ComponentsPanel.tsx
Due to the cache implemented in https://github.com/XpressAI/xircuits/pull/293, things work much faster to the point where we discovered a bug where spawning the interface would loop freeze jupyterlab. 
https://github.com/XpressAI/xircuits/pull/293
Open a canvas. Try the chain component interface. It should properly spawn and not freeze the interface.
> 🐛 Fix Component Panel Freeze on Spawn

- src/components/XircuitsBodyWidget.tsx
- src/dialog/FormDialog.tsx
- src/helpers/InputSanitizer.tsx
- ui-tests/e2e/datatype-test.spec.ts
- ui-tests/e2e/expected_outputs/01_datatypes.ts
This PR fixes the following bugs:
- fix floats to allow scientific notation
- fix floats to allow non-decimal inputs
- fix boolean dragging from ports to be always true
- fix literal chat being unable to carriage return on enter
Verify that:
1. You can input scientific notation and non-decimal inputs on floats (also on integers)
2. When you create a literal bool from a port, it will correctly display True or False
3. You can carriage return on a literal chat interface
> 🐛 Literal Input Fixes

- src/index.tsx
In https://github.com/XpressAI/xircuits/pull/290 we changed the promise we wait for, thinking that rendering will always happen after the context is ready. It turns out to be wrong when running with a remote setup. 
This change now requires that both of these promises are ready.
- https://github.com/XpressAI/xircuits/pull/290
> Await both context.ready and content.renderPromise before saving 

- src/helpers/CanvasInitializer.tsx
- src/index.tsx
This PR updates the `create a new xircuits` function to initializes a base xircuits json first, then writes it to the new file, then finally opening it. 
Previously for new canvas, after dropping the first node, the second would not appear until you save the canvas. With this PR, it should function properly.
Add if any.
> 🐛 Initialize Base Canvas For New Xircuits

- xircuits/compiler/generator.py
When using components with sub-graphs as ports, it can happen that their `.next` field is not set to None, because the `has_next` flag in the code generator is set prematurely. 
**1. Manual test**
1. Create a new Xircuits File
2. Pull in a branch component and a loop component
3. Connect the loop component to the branch components "when_true" port
4. Connect the branch component to start and finish
5. Compile
6. Observe that the loop component doesn't have a `.next = None` set up in the compiled python code
> Only set has_next to True if `.next` was actually set

- src/components/XircuitsBodyWidget.tsx
The reload all nodes function taps into reloading all nodes that were selected. This line was removed in a previous PR. 
https://github.com/XpressAI/xircuits/pull/296
**1. Test All Nodes**
1. Open a canvas, ie `ControlflowBranch.xircuits`. Update one component (ie. adding a port to the `Print` component). Reload all nodes.
2. Verify that all the modified nodes are updated.
> 🐛 Fix Reload All Nodes

- src/helpers/InputSanitizer.tsx
- xircuits/compiler/generator.py
This PR allows users to set string, secret, chat, list, tuple, dict with empty values.
**1. Test string, secret, chat, list, tuple, dict empty values** - Verify that they work as expected.
> 🐛 Allow Empty Values for Certain Data Types

- xircuits/handlers/request_library.py
- xircuits/library/generate_component_library_config.py
This fix addresses a case sensitivity issue on non-Windows OS like Linux when saving new component libraries in Xircuits. On Windows, file paths are case-insensitive, preventing files or directories with the same name in different cases. However, on Linux, this allowed for the accidental creation of duplicate component libraries with varying capitalizations. By converting library names to lowercase before saving, this update prevents such duplicates, ensuring consistent behavior across all operating systems.
https://github.com/XpressAI/xircuits/pull/309
1. Run the new xircuits library interface on a Linux. Enter a component library with mixed caps. Verify that there are no duplicate component libraries created with different caps.
> 🐛 Fix Duplicate Library Creation on Non-Windows Due to Case Sensitivity

- xircuits/start_xircuits.py
This PR hooks the xircuits launch command to display news from the[ xpressai blog](https://xpress.ai/blog) atom feed.
**1. Launch Xircuits. Verify that the blogposts notifications are accessible from the announcements icon.**
> ✨ Add XpressAi Blog Notifications 

- src/components/XircuitsBodyWidget.tsx
- src/context-menu/TrayContextMenu.tsx
- src/index.tsx
This PR enables users to copy xircuits files to the root working dir and opens it.
You can select multiple workflows at the same time.
1. Right click a non .xircuits file in the file browser. Verify that the `Copy to Root Directory` option does not spawn.
2. Right click a .xircuits file in the file browser. Verify that the `Copy to Root Directory` option does spawns, and it copies it to root and opens the workflow.
3. Try it on a workflow with the same filename in root. Verify that the alert message spawns.
> ✨ Context Menu Option to Copy Xircuits Workflows to Root

- src/components/XircuitsApp.ts
- src/components/XircuitsBodyWidget.tsx
- src/components/actions/CustomPanAndZoomCanvasAction.ts
- src/components/link/CustomLinkFactory.tsx
The old click to add point functionality grew quite annoying very quickly. In particular if we want to modify the graph to add some component, using shift+click to select a link ended up also selecting the node, because that particular behavior is meant for selecting multiple things.
By moving the add-point-to-link functionality to ctrl+click, we free up the regular click to be just a select, exactly how one expects it to be.
This also enables figma-like pinch-to-zoom and two-finger panning.
**1. Manual Test**
1. Create a link between two nodes (Start to finish is fine)
2. Click the link to select it
3. Before: Link node gets created; After: Link is selected
4. CTRL+Click the link
5. Before: Add component menu opens; After: Link node gets created
> Click Link to Select, CTRL+Click to add a Point

- src/components/XircuitsBodyWidget.tsx
- src/context-menu/CanvasContextMenu.tsx
https://github.com/XpressAI/xircuits/pull/293 implemented refactoring of the code fetching for components and the reload mechanism by implementing a cache for the component library code. However, this cache is currently only updated when the component tray button is pressed. This PR ensure that the cache is also refreshed when the "Reload Node" option is used from the right-click context menu or the "Reload All Nodes" option is selected from the toolbar.
https://github.com/XpressAI/xircuits/pull/293
Drag in a component. Update a port. Trigger reload by `Reload Node` and `Reload All Nodes`. Verify that it correctly updates.
Add if any.
> 🐛 Fix Components Not Refreshing on Reload from Canvas

- xircuits/compiler/generator.py
This pull request updates the main execution flow in the compiler to handle unrecognized command-line arguments. Previously, the script would fail when passing unknown arguments that were not explicitly handled. The change splits argument parsing to parse known arguments and ignore the rest, preventing execution failure when extra parameters are passed.
1. pass extra arguments to the compiled script, like --extra-files example.py
2. Confirm that the script executes without errors and ignores unrecognized arguments.
> 🐛 Fix compiled script run breaking on unknown arguments

- pyproject.toml
- xircuits/utils.py
`pkg_resources` which is used to copy `.xircuits` and `xai_components` to the current working dir is deprecated. This PR updates it to use importlib_resources.
Install xircuits via wheel / pip. Verify that `.xircuits` and `xai_components` are correctly saved in the current working dir.
Currently using `importlib_resources` over `importlib.resources` for py3.8 compatibility.
> ✨ Migrate from pkg_resources to importlib_resources

- xircuits/compiler/generator.py
When an input to a subxircuit is used multiple times, it is added multiple times to the InArgs by the compiler. This fixes the problem. 
**1. Manual Test**
1. Compile the attached xircuits file ([untitled7.xircuits](https://github.com/user-attachments/files/15785634/untitled7.xircuits.json))
2. Notice that the resulting python file doesn't have the input argument twice.
> Enforce that args are only picked up once for subxircuits

- src/commands/CommandIDs.tsx
- src/commands/NodeActionCommands.tsx
- src/context-menu/CanvasContextMenu.tsx
- xircuits/compiler/generator.py
This PR adds the option to open a workflow component from the workflow canvas.
https://github.com/XpressAI/xircuits/pull/289
**Test Open SubXircuits**
Create a SubXircuits. 
- create the new xircuits workflow in one of a component library dir
- save and compile
- the workflow should be available as a component 
- start a new xircuits, and drag that component in
Verify that : 
1. the option to open subxircuits only spawns on the subxircuits component
2. the subxircuits canvas is opened
3. things work as expected (can compile and run properly).
Since at core it's simply calling a workflow in another workflow, `SubXircuits` terminology is simplified to xircuits_workflow and workflow components.
> ✨ Add Open Xircuits Workflow Component Context Menu Option

- xircuits/compiler/generator.py
Usage of literal secrets failed to compile when used with dynalists because the literal handling for dynalists was missing that case. 
To resolve the problem, I've refactored the handling into a single method that is used in every place. 
**1. Manual Test**
1. Try to compile [secret-dynaport-compile.xircuits.json](https://github.com/user-attachments/files/15800530/secret-dynaport-compile.xircuits.json) 
2. Without the fix it breaks, with the fix it works.
> Fix literal secret handling in Dynalists

- xai_components/base.py
- xai_components/xai_utils/RunParallelExample.xircuits
- xai_components/xai_utils/utils.py
- xircuits/compiler/generator.py
A long standing issue with Xircuits is that we can only really do things in serial. One of the reasons for that is that the component connections are all set up at initialization. When we run things in parallel, that setup results in concurrent reads and writes.
This PR introduces `__copy__` and `__deepcopy__` implementations for `InArg`, `OutArg`, `InCompArg` and `BaseComponent` as well as a connection setup that will continue to work with copies. 
Allowing copies of a sub-graph thereby allows us to run them in parallel. An utility component `RunParallelThread` can be used together with any iterating component to easily enable parallel execution of that iteration. This is especially useful when it is IO heavy. 
As this PR includes changes to `xai_components/base.py` and compiler changes …
> Introduce Parallel Execution Component and Make Args & Components Copyable

- xai_components/xai_utils/RunParallelExample.xircuits
- xai_components/xai_utils/utils.py
In #332 we added a `RunParallelThread` Component. If within its body another thread is started, we can run into the situation where the interpreter wants to shutdown but there are still futures that need to be executed that in turn want to create more futures. 
That fails with `RuntimeError: cannot schedule new futures after interpreter shutdown`. 
We didn't run into the issue at first, because a Jupyter kernel keeps running until the output panel is closed. But, when we directly run the compiled file from the terminal we can reproduce the exception. 
The solution to the issue is to await the futures before finishing the main thread. We therefore introduce an `AwaitFutures` Component that will wait for a list of futures, and extend `RunParallelThread` to expose both the future it has just …
> Allow waiting for futures

- src/XircuitsWidget.tsx
- src/commands/CustomActionEvent.tsx
- src/components/XircuitsApp.ts
We've run into the issue that the xircuits widget would handle event's that aren't meant for it (e.g. copy & paste in a text editor would result in the widget pasting things that may have been copied previously). 
At the core of the issue lies the event handler being attached to document, but as that is being done by the underlying diagram engine, we can't change that as easily. 
As a workaround, we're passing a way to acquire the widget id down to the event handler, so it can check if it is supposed to handle the event. 
We must pass on a function instead of giving it the id directly, because the id isn't yet available during construction.
**1. Manual Test**
1. Open a Xircuits Diagram, create a node and copy it (no need to paste yet)
2. Open a Text editor and press CTRL + V
3. Switch …
> Only handle events for the correct widget

- src/components/node/CustomNodeWidget.tsx
As workflow components are unique and integral parts of the system, they require a distinct appearance to differentiate them from other components. 
In the process, the node widget code has been significantly refactored. The previous implementation in `CustomNodeWidget` was a monolithic ball of mud, making it difficult to manage and extend. The refactoring process involved breaking down the `CustomNodeWidget` into smaller, more manageable functional components, `CommentNode`, `ParameterNode`, `StartFinishNode`, `WorkflowNode`, and `ComponentLibraryNode`.
1. Verify that workflow components now have a distinct appearance compared to other nodes.
2.  Verify that the previous functions of nodes are still intact, which includes:
- `CommentNode`: double clicking will update
- `ParameterNode`: …
> ✨ / ♻️  Add Workflow Component CSS + Refactor Node Widget Code  

- src/commands/NodeActionCommands.tsx
- src/dialog/FormDialog.tsx
- src/dialog/LiteralInputDialog.tsx
- src/tray_library/GeneralComponentLib.tsx
In https://github.com/XpressAI/xircuits/pull/340 we have added support for attached literals. 
However, as @MFA-X-AI has pointed out, we didn't properly support copy & paste on them. Attached literals didn't get copied with the node they were attached to. 
This PR adds this functionality.
- https://github.com/XpressAI/xircuits/pull/340
> Copy & Paste support for Attached Literals

- package.json
- src/XircuitsFactory.ts
- src/commands/CommandIDs.tsx
- src/commands/LibraryActionCommands.tsx
- src/components/node/CustomNodeWidget.tsx
- src/components/port/CustomPortLabel.tsx
- src/context-menu/ComponentsPanel.tsx
- src/context-menu/TrayContextMenu.tsx
- src/index.tsx
- src/tray_library/NodePreview.tsx
- src/tray_library/Sidebar.tsx
- src/tray_library/TrayItemWidget.tsx
- src/ui-components/icons.tsx
- style/Sidebar.css
- style/base.css
- ui-tests/README.md
- ui-tests/e2e/datatype-test.spec.ts
- xai_components/xai_controlflow/branches.py
- yarn.lock
When looking for a component in the library, it can be very helpful to see its documentation (if any) and a preview of the component node. 
| Without Docstring | With Docstring | Nested Workflow |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/4a7b3b23-683a-4feb-976e-32a1b7a1e721) | ![image](https://github.com/user-attachments/assets/a99012ad-ec67-4674-9e7b-e8218722d531) | ![image](https://github.com/user-attachments/assets/1eb36d92-bc4c-434e-823c-5d2c0e933539) |
This PR enables a documentation preview on hovering over a component. It also includes a change to the search functionality, such that the doc string is now also considered when searching for something.
While polishing the PR, I realized that it isn't all that hard now to show the nodes in the …
> Overhaul Component Library

- src/tray_library/Sidebar.tsx
It can take quite a while to render all preview nodes when the user types in a search query, in particular on the first few letters when there are still potentially a lot of results.
This PR introduces a short delay (150ms) before the search is actually executed.
> Delay search based re-render until user has stopped typing

- src/commands/LibraryActionCommands.tsx
- src/tray_library/Sidebar.tsx
This PR adds ExampleComponent when creating a new component from the tray sidebar interface.
```
from xai_components.base import InArg, OutArg, InCompArg, Component, BaseComponent, xai_component, dynalist
@xai_component(color='blue')
class ExampleComponent(Component):
"""Brief description of the component.
- input_port (type): Description of input_port.
- output_port (type): Description of output_port.
"""
input_port: InArg[type]
output_port: OutArg[type]
def execute(self, ctx) -> None:
input_port = self.input_port.value
print(f'The input_port value is {input_port}.')
self.output_port.value = input_port
```
https://github.com/XpressAI/xircuits/pull/343
1. Create a new component. Ensure that the template appears on the text editor. 
2. Drag it in. Ensure that it works.
> ✨ Add component example template when creating from sidebar interface

- xai_components/xai_controlflow/ExceptionHandlerExample.xircuits
- xai_components/xai_controlflow/branches.py
- xai_components/xai_utils/utils.py
This PR adds `ExceptionHandler` component. Useful for workflows that might hit an exception. This component allows users to handle it gracefully. Attach the main execution to its body branch, and if it hits an exception it will continue on the exception branch, with the exception message. It will then continue with the main execution whether it hits the exception or not.
1. Run the ExceptionHandlerExample.xircuits workflow. Ensure it executes as expected.
2. run any other workflows that may run into exceptions. Ensure that the ExceptionHandler component can handle it as expected.
> ✨ Add ExceptionHandler component

- src/commands/NodeActionCommands.tsx
The smart link action happens when a flow link is created between two nodes. It autoconnects the two nodes' parameter ports that have a shared string, eg: out_sparksession -> in_sparksession.
This PR updates it so that:
- when a flow link is created, it will check if the port type matches, eg `str`-> `str`, `any` -> `any`
- it will allow port linking if an arbitrary datatype is connected to an `any` type, ie `str` -> `any`. Vice versa does not apply, ie `any` -> x `str`. 
A link should not be created if:
- the port type does not match (with the exception of `any`) 
- the source OR the target port already has a link (previously it would overlay an additional link)
https://github.com/XpressAI/xircuits/pull/153
Verify the smart link logic:
- type checks
- type checks with `any`
- port …
> 🐛 Smart Link Fixes

- src/commands/NodeActionCommands.tsx
- src/components/port/CustomPortLabel.tsx
- src/components/port/CustomPortModel.ts
This PR fixes the following:
- fix union link logic if passed from non-literal: as node to node parameter linking is now fixed in https://github.com/XpressAI/xircuits/pull/348 , the handling for Union needs to be addressed. This PR now properly parses each type in the Union (ie InArg[Union[str|int]]) and allows linking if one datatype mathces.
- fix smart link not considering compulsory symbol: previously the compulsory [★] affects the smartlinking. Now this PR strips the ★ before matching. 
- fix smart link if using chain linking: as flow ports do not have data types, this PR properly handles it.
- fix union symbol from not appearing in ports: previously Union type was internally set if there's a `.`. This PR properly recognizes it if type `Union` is passed. …
> 🐛 Union Type Fixes + More Smart Link Fixes

- package.json
- src/commands/CommandIDs.tsx
- src/helpers/HelpResources.tsx
- src/index.tsx
- yarn.lock
This PR adds Xircuits documentation options to the Help menu bar.
1. Test that the options are present and they link to the correct documentation
> ✨ Xircuits Help Options 

- src/components/XircuitsBodyWidget.tsx
- src/dialog/RunDialog.tsx
This PR fixes:
- duplicate form inputs spawning when toggling remote run dropdown
- camel caps in arguments not handled properly 
- Drag in an argument component.  Save, compile, run it to see the number of input forms. Toggle the run type. Run it again. Ensure that the number of form inputs are the sam
- Drag in an argument component. Use camelcaps. Compile and run. Verify that the output contains the input provided.
This PR is a WIP of a bigger update of updating the remote run feature.
> 🐛 Fix Argument CamelCap Handling + Remote Run Input 

- xai_components/base.py
- xircuits/compiler/generator.py
The current way the compiler handles boolean arguments looks like this:
```python
parser.add_argument('--testArgs', type=bool)
```
Unfortunately, this means that regardless of what is passed to `--testArgs`, whether it's False or 0, it's first converted to a string and then passed to the `bool()` function, hence always evaluating to True.
This PR adds `parse_bool` to `base.py` to handle this issue. The new implementation looks like this:
```python
parser.add_argument('--testArgs', type=parse_bool, default=None, nargs='?', const=True)
```
What this does:
- It will return False if provided with 'false', 'f', 'no', 'n', or '0' (not case-sensitive).
- If the argument is not provided at all, it will be None.
- If the flag is provided without a value (like just `--testArgs`), it will be True. …
> 🐛 Handle Boolean Arg Parsing in Compiler

- src/commands/CommandIDs.tsx
- src/index.tsx
This PR allows users to compile a workflow / multiple workflows from the Jupyterlab context menu. Under the hood it calls the xircuits compile backend endpoint. It also pushes the xircuits related context menu to the top.
1. Boot up **Xircuits**.
2. Right-click any workflow from the file browser to open the context menu.
3. Select **Compile**.
4. Verify the following:
- **a.** The workflow compiles properly.
- **b.** The workflow runs as expected.
1. Boot up **Xircuits**.
2. Select multiple workflows from the file browser.
3. Right-click to open the context menu.
4. Select **Compile**.
5. Verify the following:
- **a.** All selected workflows compile properly.
- **b.** All selected workflows run as expected.
> ✨ Add Compile Xircuits to Context Menu

- src/commands/CustomActionEvent.tsx
This PR adds event handling logic to fully stop keyboard event propagation (`preventDefault()`, `stopPropagation()`, `stopImmediatePropagation()`) in `CustomActionEvent`. This ensures key commands like `Ctrl+Z` only affect the active xircuits canvas and do not interfere with other JupyterLab widgets like text editors when they are not active.
https://github.com/XpressAI/xircuits/pull/254
1. Verify that `Ctrl+Z`, `Ctrl+Y`, etc., only impact the active Xircuits canvas.
2. Confirm that no other JupyterLab widgets, such as the text editor, are affected by key commands while the Xircuits widget is focused.
> 🐛 Prevent Event Propagation to Other Widgets

- src/commands/NodeActionCommands.tsx
- src/components/node/CustomNodeWidget.tsx
- src/tray_library/GeneralComponentLib.tsx
Currently when a node is pasted from another canvas, the inPort type will be `""` due to an unimplemented deserialization method. The simplest way around this is to simply trigger a reload on the pasted node which refetches the node information. While implementing this, I've also enabled reload to be used on parameter nodes, which was previously disabled due to it crashing the interface when reloaded.
https://github.com/XpressAI/xircuits/pull/251
1. Copy paste a node from one canvas to another. Connect a literal / argument to it. Verify that it can be correctly connected.
2. Trigger a reload on a parameter component / using reload all. Verify that on the console window, it doesn't log that Literals / Arguments cannot be reloaded.
> 🐛 / ♻️ Fix Node Cross Canvas Pasting + Enable Reload for Parameter Nodes

- xircuits/compiler/compiler.py
This PR raises an exception for errors during compilation. Previously, any exceptions that occurred during the compilation process were caught and printed, but the compilation would continue, which could cause issues downstream if the compilation did not complete as expected. The code has been updated to raise a `ValueError` after catching an exception, which will rightfully terminate the process and notify the error.
To verify this change, the following tests were conducted:
**1. Compilation Test via CLI**
1. Attempt to compile an uncompleted diagram using the CLI.
2. Ensure that compilation fails and raises a `ValueError` with the correct message.
**2. Compilation Test via Xircuits Canvas**
1. Attempt to compile an uncompleted diagram from the Xircuits Canvas.
2. Verify that the process …
> 🐛 Raise Exception in Compile Failure

- xircuits/handlers/request_folder.py
This PR fixes the CLI bug that incorrectly parses component library github URLs that are **not** in our recognized library list, when running
```
xircuits install https://github.com/your-orgs/the-xai-lib-name
```
Run xircuits install <github-url> from a url. Confirm that it correctly installs the library.
> 🐛 Fix CLI Component Library Install when using Github URL

- pyproject.toml
- xai_components/base.py
A couple of libraries have made the move to async execution, using them from within Xircuits is quite cumbersome and error prone at the moment. 
This introduces an AsyncComponent that can be used as the parent class which allows `execute` method to be defined as `async`.
As a bridge between sync and async we need another dependency: `asgiref`. It provides `@sync_to_async` and `@async_to_sync`.
> Add asyncio support with AsyncComponent

- src/components/XircuitsBodyWidget.tsx
- src/context-menu/ComponentsPanel.tsx
This PR implements several UI/UX improvements for the Xircuits Canvas interface:
1. Fixed component panel chain link interface to allow deleting search text by preventing propagation
2. Prevented component panel from spawning from Literals nodes
3. Added ability to dismiss component panel and context menu via Escape key
4. Fixed component panel and context menu min-height inheritance issue that was causing click-blocking
5. Implemented viewport clamping to prevent component panel from being clipped off-screen
It also adds a shadow to component panel and context menu.
**1. Chain Link Search Deletion Test**
```
1. Create a chain link and open search interface
2. Type and attempt to delete text
3. Verify text deletion works without canvas interference
```
**2. Literal Node Component Panel …
> 🐛 / ✨ Component Panel: Fix Clipping, Add Escape Key, Improve Interactions

- src/commands/CommandIDs.tsx
- src/index.tsx
This PR allows user to create a new Xircuits from the Jupyterlab filebrowser context menu.
1. Right click on the Jupyterlab file browser. Verify that the Create New Xircuits option is there.
2. Create a new Xircuits using that option. Verify that it works as expected.
> ✨ Add Create New Xircuits to Jupyterlab Filebrowser Context Menu

- src/commands/CommandIDs.tsx
- src/components/XircuitsBodyWidget.tsx
- src/components/runner/RunSwitcher.tsx
- src/index.tsx
This PR allows users to automatically run a compiled xircuits workflow on the terminal. It will spawn a terminal, cd to the jupyterlab base working dir, export the python path, and run the compiled python workflow there. Useful for workflows that can't run properly on the a single threaded python kernel or workflows with interactivity.
https://github.com/user-attachments/assets/f889a045-ddb0-4cd9-946c-9100edd38707
1. Compile a Xircuits workflow. Select the `Run from Terminal` option. Run it.
2. Verify that it works as expected.
> ✨ Add Run Xircuits Workflow on Terminal Option

- .github/workflows/run-ui-tests.yml
- src/components/XircuitsBodyWidget.tsx
- src/context-menu/TrayContextMenu.tsx
- src/index.tsx
- xircuits/start_xircuits.py
This PR:
- Sets the tray component library install to run in the terminal instead of the output viewer.
- Uses the `xircuits install libraryName` command for installation (now case-insensitive).
- **CLI Update:** When running non-init commands, Xircuits now traverses upward to locate the working directory (the folder containing both `.xircuits` and `xai_components`) and switches to it before executing the command.
- **CLI Update:** If the working directory isn’t found, Xircuits auto-initializes if the `XIRCUITS_INIT` environment variable is set or prompts the user to initialize in the current directory.
- Removes automatic initialization on module import so that initialization occurs only when needed.
https://github.com/user-attachments/assets/71fbf883-4bd0-4ce0-824e-bfd3cf6d4d28 …
> ♻️ Set Component Library Install to Run on Terminal

- src/components/port/CustomPortLabel.tsx
This is a simple graphical bug fix.
Before:
After;
It isn't a huge change, but makes things look the same in the component preview and the canvas. Also start components without any inputs now look a bit less awkward.
> Align inputs on the left and outputs on the right.

- src/commands/CommandIDs.tsx
- src/components/XircuitsBodyWidget.tsx
- src/index.tsx
- xircuits/compiler/compiler.py
- xircuits/start_xircuits.py
This PR introduces several improvements to Xircuits workflow execution and compilation:
1. Added a new `xircuits run` CLI command for direct workflow execution. You can pass `xircuits run workflow.xircuits` or `workflow.py`. If the former, it will compile it first.
2. Enhanced FileBrowser integration with new "Run Xircuits" context menu option
3. Made "Copy to Root" option only visible for non-root workflows
4. Fix recursive compilation to better handle working directories (previously it it was run from a non-base working dir, it wouldn't work as expected)
5. Modified working directory detection to use xai_components as the main reference
6. Updated terminal execution to use the new `xircuits run` command
These changes make workflow execution more streamlined and intuitive while fixing …
> ✨/🐛  Add xircuits Run CLI Command +  Fix Recursive Compile

- src/components/XircuitsBodyWidget.tsx
- src/index.tsx
Fixed an issue where the arguments dialog would show empty arrays when triggering compile-run directly on a dirty (unsaved) model. This was happening because the state variables that feed the args dialog were only being updated when the initialize flag was true.
The fix adds a helper function `getArgumentNodes()` that recalculates the current argument nodes just before opening the dialog, ensuring the dialog always has up-to-date values regardless of model state. This was implemented in both `handleLocalRunDialog` and `handleRemoteRunDialog`.
This PR also removes the alert after compiling. 
N/A
**1. Test Compile-Run on Dirty Model**
1. Open a Xircuits workflow
2. Add some argument nodes
3. Make changes without saving
4. Click compile-run
5. Verify that arguments appear correctly in dialog …
> 🐛 Fix Argument Inputs not appearing in unsaved / uncompiled Run Dialogues

- xai_components/xai_utils/utils.py
Adds some regular expression components to Utils that can be very useful.
Welcome to Xircuits! Thank you for making a pull request. Please ensure that your pull request follows the template.
Please include a summary which includes relevant motivation and context. You may also describe the code changes. List any dependencies that are required for this change.
**1. Test A**
1. First step
2. Second step
3. ...
Add if any.
> Add Regex components to utils.py

- xai_components/base.py
- xircuits/compiler/generator.py
Sometimes it is quite hard to know what exactly is going on during the execution of a Xircuits file. 
This implements a proof of concept for a structured debug logger. It outputs its log in a json lines format that is readable by json log tools like [fblog](https://github.com/brocode/fblog).
For example:
The execution of a simple xircuits file like this produces the following output:
```
{"timestamp": "2025-02-24T18:02:48.109280", "level": "DEBUG", "type": "before_execution", "component": {"class": "ConcatString", "id": "3d8d1923-f750-4c77-875f-2922a2efcceb", "inputs": {"a": "Hello ", "b": "World!"}}, "ctx": {"args": "Namespace()"}}
{"timestamp": "2025-02-24T18:02:48.109280", "level": "DEBUG", "type": "after_execution", "component": {"class": "ConcatString", "id": …
```
> PoC for Structured Debug Logging

- xircuits/compiler/generator.py
With #384 we've added the support for structured logging. This logging requires that each component has a well defined id. 
We assumed that just defining this on `BaseComponent` as a constructor parameter would be enough to get the rudimentary support going. But it turns out that Components with custom constructors didn't like being instantiated with the id in the call parameters.
In particular the Workflow Components that the compiler creates didn't support it. But there are also a couple of other components that have the same issue.
This PR fixes the compiler to emit Workflow Components that will accept an id as a constructor parameter, but also moves the id assignment to be done with an additional property based call.
Ideally, we want to move the id assignment back to the component …
> Fix id setting issue

- xai_components/base.py
In more complex scenarios it may happen that the component that is passed into the debug logger is a SubGraphExecutor itself. 
This PR adds the handling for that case.
> Another debug logging fix

- src/components/XircuitsBodyWidget.tsx
- xircuits/start_xircuits.py
This pull request addresses an issue with relative path resolution in the run command. Previously, if the run command was executed from a subdirectory, the relative paths could resolve incorrectly after changing the working directory to the Xircuits base directory. This PR captures the original working directory before switching directories, ensuring that relative file paths (for source and output files) remain accurate. 
N/A
The changes were tested by running the workflow commands from different subdirectories. The relative paths were resolved correctly, ensuring that the run command executed the appropriate files.
**1. Test A**
1. Create a workflow that uses a workflow component in a subdir (e.g., `xai_components/xai_controlflow`) within your Xircuits project.
2. Open a terminal in the …
> 🐛 Fix relative path resolution in xircuits run command

- .github/workflows/run-cli-tests.yml
- tests/tests.py
- xircuits/library/list_library.py
This PR introduces a new set of CLI test cases under `tests/tests.py` to improve the test coverage of core functionalities.  
Additionally, a new GitHub Actions workflow file `run-cli-tests.yml` was added under `.github/workflows/` to automate running these tests.  
The goal is to ensure CLI components behave as expected and are tested on every push, pull request, or manual dispatch across multiple Python versions.  
---
This PR also fixes an issue where installed libraries were incorrectly marked as incomplete (`[*]`) when listed using `xircuits list`, despite being properly installed.  
The issue occurred because the `check_requirements_installed` function was comparing the full requirement string (e.g., `"sendgrid==6.11.0"`) with the list of installed package names obtained from `pip …
> Add new tests

- src/index.tsx
- ui-tests/tests/arg_input_ui_test.py
- ui-tests/tests/parameter-names-autoshift.py
- ui-tests/tests/parameter-names-despawn.py
- ui-tests/tests/parameter-names-spawn.py
- ui-tests/tests/protected-nodes-and-lock-test.py
- ui-tests/tests/remote_run_arguments_test.py
This PR introduces the following enhancements to the Xircuits Launcher:
---
Adds a new section in the Launcher to display curated example templates like Agent and Service workflows. Each button:
- Installs required component libraries via terminal
- Opens a fresh copy of the workflow file (non-destructive)
- Automatically refreshes the component list
---
A reusable function to add example buttons to the Launcher with custom labels, paths, and ranks.
---
Automatically loads and displays all `.xircuits` files found in the `.xircuits/templates/` folder.
- Each template opens in a new untitled file
- Section is hidden if the folder is missing or empty
---
Ensures:
- `"Xircuits Templates"` always appears first
- `"User Templates"` appears second if available
---
To verify the changes:
1. …
> Add launcher support for Xircuits templates and user templates

- src/components/XircuitsBodyWidget.tsx
- style/base.css
This PR implements one-way theme synchronization between Xircuits and JupyterLab:
- When the user toggles the theme from the Xircuits toolbar, JupyterLab's theme is updated accordingly (Light or Dark).
- Added a slight delay before updating Xircuits theme to prevent visual mismatch during JupyterLab’s theme transition.
Note: Changes in JupyterLab’s theme settings will not affect Xircuits — sync is one-way only (Xircuits → JupyterLab).
> Sync JupyterLab theme with Xircuits toggle

- src/index.tsx
- Switched library presence check from folder-based detection to using the `get_config` endpoint.
- Replaced terminal-based library installation with a more stable API-based flow.
- Fixed a case where the launcher sections were not reordered correctly after auto-opening.
> ✨ Migrate library checks to get_config & API-based installs + 🐞 Fix launcher section reorder

- src/components/XircuitsBodyWidget.tsx
- src/components/link/LinkSplitManager.ts
- src/components/link/SplitLinkCommand.ts
- src/components/state/MoveItemsState.ts
This PR introduces a new feature that allows users to drag and drop a component directly onto an existing connection, automatically splitting the link and inserting the component in between — whether the component is dragged from the sidebar or from within the canvas itself.
https://github.com/user-attachments/assets/9bbdfe88-bfe0-49fe-b7a8-21a0bbd4de80
- Detects when a node is dragged over a valid link (`out-0 → in-0`) using \`LinkSplitManager.detectLinkUnderPointer\`.
- Highlights the hovered link using the \`.hover\` class.
---
- Introduces \`SplitLinkCommand\` that:
- Validates required ports (\`in-0\`, \`out-0\`) on the dragged component.
- Removes the original link and reconnects:
- \`source → draggedNode.in-0\`
- \`draggedNode.out-0 → target\`
- Ensures existing links on affected …
> ✨ Implement "Drop Node on Link" feature

- src/commands/NodeActionCommands.tsx
- src/tray_library/Component.tsx
- src/tray_library/Sidebar.tsx
- xircuits/handlers/components.py
This PR Improves error toasts for Python components by showing detailed info (file path, line number and error type)
- Reverted the component parsing saving notification, and replaced it with JupyterLab notification.
- Structured the toast message to display the file path, line number, and error type by utilizing the new error_info returned from the backend.
**1. Test: Triggering Toast Notification on Syntax Error**
1. Created a test Python component file with a forced `SyntaxError` (e.g., missing colon or invalid expression).
2. Saved the file to trigger parsing via Xircuits component loader.
3. Observed toast notification showing:
* Full file path
* Exact line number
* Error type and message
> revert comp parser notif

- src/components/XircuitsBodyWidget.tsx
On the very first contentChanged event the handler only clears undo history and registers listeners - but for some reason it never called engine.setModel(). Which means that it would only render the default “Start/Finish” template until a second change event finally applies the updated model. Under heavy CPU throttling that second event can be delayed or even skipped, leaving us with a blank canvas.
(Hopefully this fixes things)
1. Open JupyterLab and load an existing .xircuits file that has more than just the default “Start” and “Finish” nodes.
2. In Chrome DevTools, set CPU throttling to “Slow 6×”.
3. Refresh the JupyterLab page (⌘R or F5).
4. Observe that the canvas stays on the empty/default template (only “Start”/“Finish”), instead of rendering your saved nodes.
1. With the same …
> 🐛 Fix Workflow Not Rendering on Refresh on Slow CPUs

- src/commands/NodeActionCommands.tsx
- src/components/XircuitsBodyWidget.tsx
- src/components/node/CustomNodeWidget.tsx
- src/components/port/CustomPortModel.ts
- src/helpers/notificationEffects.ts
1. This PR replaces all instances of error tooltip bubbles (`ReactTooltip`) with standardized `Notification.error` calls:
* Removed all tooltip-based error messages (mainly using `extras["tip"]`).
* Replaced them with `Notification.error` displaying the same message.
* Preserved visual highlighting via `borderColor = "red"` and `node.setSelected(true)` where applicable.
* Removed one redundant `Notification.error` call for `[★]COMPULSORY InPorts` check to avoid duplicate error messages when running workflows.
2. Standardized error notifications with action buttons for better UX:
* Introduced a new showNodeCenteringNotification() helper function.
* This function displays an error message using Notification.error(...), and includes a "Center" button.
* Clicking the "Center" button …
> Replace ReactTooltip with Notification.error + add Center action button

- src/components/XircuitsBodyWidget.tsx
- xircuits/compiler/validation.py
- xircuits/start_xircuits.py
This PR introduces:
- Error message for unconnected [★] compulsory InPorts during save and compile in the GUI (previously only shown on run).
- CLI-level warning via enforce_compulsory_ports without blocking compilation.
- No breaking behavior; compilation and save continue as usual.
**1. GUI: Save and Compile with unconnected compulsory ports**
1. On the canvas, leave a component that has a [★] compulsory InPort unconnected.
2. Click **Save**:
- You will see a success notification: `Workflow saved successfully.`
- You will also see an error notification: `Please make sure the [★]COMPULSORY InPorts are connected.`
3. Click **Compile**:
- You will see a success notification: `Workflow compiled successfully.`
- You will also see the same error notification about unconnected compulsory …
> Show notif for unconnected compulsory ports  and warning in CLI

- src/commands/NodeActionCommands.tsx
This PR fixes an issue where Comment nodes and other nodes without a valid component path were triggering unnecessary error notifications during the reload process.
- Verified that Comment nodes no longer show error notifications on reload.
- Confirmed that regular components still reload correctly and show appropriate error messages when needed.
> 🐛 Skip reload for Comment nodes

- src/context-menu/TrayContextMenu.tsx
This PR fixes a bug where the "Uninstall" option still appeared in the context menu for core libraries such as CONTROLFLOW, even though they are supposed to be protected.
The issue was due to comparing the raw libraryName with the CORE_LIBS set, while normalizeLibraryName() was returning a path-like string (xai_components/xai_controlflow). The fix extracts the last part of the path using .split('/').pop() before comparing.
**1. Test core library context menu**
1. Go to the "Libraries" panel in the sidebar.
2. Right-click on a known core library (e.g. `CONTROLFLOW`).
3. Verify that the **"Uninstall"** option **does NOT appear** in the context menu.
**2. Test non-core library context menu**
1. Right-click on a non-core library (e.g. `actors`, `gradio`, etc.).
2. Verify that the …
> 🐛 Fix: hide uninstall option for core libraries

- src/components/XircuitsBodyWidget.tsx
This PR fixes the `run w/o compile` run option. 
**1. Check Run without Compile Functionality**
1. Open canvas, save compile run. Verify that it works normally.
2. Make a change (eg change a value of a Literal String). Select the `run w/o compile` option. Verify that the output does not reflect the newest changes (same output as previous)
> 🐛 Fix Run Don't Compile Option

- .github/workflows/run-ui-tests.yml
- ui-tests/tests/test_clipboard_copy_paste.py
- ui-tests/tests/test_toggle_light_dark.py
- ui-tests/tests/xircuits_test_utils.py
This PR introduces two Playwright UI tests focused on stability and official signals:
- Clipboard test on a single Print node (Copy, Paste, Cut).
- Light/Dark toggle test using JupyterLab official theme signals.
Includes new helpers in xircuits_test_utils for toolbar clicks, node selection, count waits, and theme checks.
To run the test locally, please follow the setup and usage instructions in the  [README.md](https://github.com/XpressAI/xircuits/blob/master/ui-tests/README.md) file 
> 🧪 Add Playwright tests: Clipboard + Light/Dark toggle

- xircuits/library/__init__.py
- xircuits/library/list_library.py
- xircuits/library/update_library.py
- xircuits/start_xircuits.py
- xircuits/utils/git_toml_manager.py
This PR implements a new `xircuits update` command that allows users to safely update installed component libraries with automatic backup creation. The update process preserves local modifications by creating timestamped `.bak` files before overwriting changed files.
Key features:
- **Safe updates**: Creates `.bak` backups of modified files before overwriting
- **Flexible source resolution**: Uses pyproject metadata, explicit repo URLs, or falls back to index manifest
- **Selective pruning**: Optional `--prune` flag to archive local-only files
- **Dry-run support**: Preview changes without modifying files, generates unified diff
- **Automatic dependency management**: Updates pyproject extras and installs requirements
- **Git integration**: Supports specific refs (tags/branches/commits) …
> ✨ CLI Support for Updating Component Libraries

- src/components/link/LinkSplitManager.ts
- src/components/link/SplitLinkCommand.ts
This PR addresses the issue where dropping a node on a flow link caused **all its parameter connections (e.g., to literals)** to be lost. If a node had parameter links already attached, they were completely removed during the split.
* Keep parameter links intact when inserting a node on a link.
* Added a **sanitization step** that checks parameter links *after insertion* and removes **only unsafe ones** (those that create execution loops/back-edges).
* Ensures flow ports (`in-0/out-0`) are reconnected correctly, while parameter links remain unless invalid.
**1. Preserve parameter links on drop**
1. Create a workflow with a node connected to a literal through a parameter port.
2. Drag another node and drop it on an existing flow link.
3. Verify that the parameter link to the literal is …
> ✨ Preserve parameter links on "Drop On link" remove only unsafe loops

- src/commands/NodeActionCommands.tsx
- src/helpers/notificationEffects.ts
This PR refines and simplifies the handling of **missing components** on the Xircuits canvas by switching to a more **robust and deterministic detection** mechanism based on `library_id`  provided by the backend 
* **Reliable library detection:**
* Introduced `pathToLibraryId()` to extract a candidate `library_id` from the component path.
* Components are now matched **strictly** against `library_id` from the backend config returned by `library/get_config`.
* Reused the existing normalizeLibraryName() utility for consistent ID normalization across the codebase
* **Accurate remote detection:**
* Remote status is determined **solely** based on the backend's `status` field (`status === "remote"`).
* **Improved install prompt logic:**
* The button label now uses the original backend …
> ✨ Improve missing component handling V2
