XpressAI/xircuits

.xpipes/config.ini
MANIFEST.in
src/components/xpipeBodyWidget.tsx
src/components_xpipe/Component.ts
src/components_xpipe/Sidebar.tsx
src/components_xpipe/TrayItemWidget.tsx
src/components_xpipe/TrayWidget.tsx
src/debugger/DebuggerWidget.tsx
src/index.tsx
xai_components/.xpipes/config.ini
xpipes/handlers.py
xpipes/start_xpipes.py

- Allow base path to be configured through editing config.ini file.
- To test:
1. Changing the base path should reflect to the sidebar component.
2. Putting "" or '' should point to the root file.

Adding xpipes config for the base path

---

src/components/xpipeBodyWidget.tsx
src/components_xpipe/Component.ts
src/kernel/panel.ts
xai_components/base.py
xai_components/xai_learning/component_test.py

**Description**
1. Added a new compulsory input port/argument. There will be a [★] at the front of the name/label of the InPort. By compulsory means that if the InPort is not connected to any node, the xpipes won't be able to run. 
2. Added an error tooltip if the node are not connected properly. 
3. Added an icon for Output Panel.
**Test**
1. Please check how the compulsory InPort is used in `CompulsoryHyperparameter`'s component. 
2. Please check if the `xpipes` is working as expected if the `InCompArg` are connected.
3. Please check what happen if the `InCompArg` are not connected. There will be a tooltip that display an error's message on the related node when hovered. Connect a link to that port will remove the tooltip.
4. Also, please check the error tooltip when the triangle link …

✨Add Compulsory InPort 

---

style/toggle.css

Increase lock size and align to centre
Before:
After:

💄Update lock UI

---

xpipes/handlers/components.py

Changed it in the Github webinterface, but in principle it should work.

Reload location from config on each request

---

src/components/xpipeBodyWidget.tsx

This simply refactors the repetitive code for connecting signals into a higher order function and a list of signal handler pairs.

Refactor Signal Connecting

---

src/components/CustomNodeWidget.tsx

This will allow the links stay connected when editing literal node
Improve #95 
1. Make sure the literal node are linked before editing it.
2. Try linking to multiple ports before editing the literal node.
3. Try to run xircuits after editing it.

✨Enable editing literal keep linked

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This pull request adds templates for bug reports, feature requests and contributors.
Read these mds:
1. contributing.md
2. .github/ISSUE_TEMPLATE/bug-report.md
3. .github/ISSUE_TEMPLATE/feature-request.md
and let me know what you think. :D

✨ contributor update (templates for bugs, feature requests, and contributors)

---

src/components/xircuitBodyWidget.tsx

This will avoid the component and action panel from going off screen.
1. Open **component panel** either via dropped link or right-click anywhere on canvas.
1. It shouldn't display off canvas.
2. Also, do the same for **action panel** (ctrl+left-click)
1. It shouldn't display off canvas.

⚡️Dynamic positioning of panel from going off canvas

---

examples/AutoMLBasicBinaryClassification.xircuits
examples/AutoMLBasicMulticlassClassification.xircuits
examples/AutoMLBasicRegression.xircuits
examples/AutoMLClassificationBlendModels.xircuits
examples/AutoMLRegressionStackModels.xircuits
package-lock.json
tsconfig.tsbuildinfo
xai_components/xai_pycaret/classification.py
xai_components/xai_pycaret/regression.py
xai_components/xai_pycaret/utils.py

Pycaret components for ML regression tasks, including the most commonly used Pycaret functions, 2 examples xircuits for regression models.    
N/A
1. compile and run <code>AutoMLBasicRegression.xircuits</code> 
2. compile and run <code>AutoMLRegressionStackModels.xircuits</code> 
3. compile and run pycaret classfication examples 
4. create new Xircuits using the available regression components  
N/A

📉 Pycaret Regression Components + Examples

---

src/components/XircuitsApp.ts

This will save selected node when detecting change.
As this bug was found and mostly noticeable on @MFA-X-AI's laptop, I think it's better if @MFA-X-AI is the one to test what causing the bug and does this PR fix the issue.

🐛Fix nodes being de-selected due to dirty state

---

xai_components/xai_controlflow/branches.py
xai_components/xai_utils/utils.py

Adds some typing and useful components to the base component library.

Add concat component and add typing.

---

xai_components/base.py

Quick fix to update some types in base class methods.

Update typing to match current usage.

---

examples/ControlflowBranch.xircuits
examples/ControlflowCounterLoop.xircuits
examples/ControlflowLoop.xircuits
xai_components/base.py
xai_components/xai_controlflow/branches.py
xai_components/xai_template/example_components.py

This PR:
- adds and updates 3 examples of how to play with the new controlflow components. 
- updated the branch component logic to allow the flow to return to the original path, ie `do` -> `then` logic. 
- removed broken / old template components
https://github.com/XpressAI/xircuits/pull/193
Run all 3 new examples
- ControlflowBranch.xircuits
- ControlflowLoop.xircuits
- ControlflowCounterLoop.xircuits 
Ensure that it can run completely until the end and their output is as expected.

▶️ Controlflow Example Workflows

---

README.md
package-lock.json
package.json
xai_components/readme.md

1.7 release PR. Also updated readmes with the new xai component libraries.

1.7 Release 

---

.gitmodules
MANIFEST.in
README.md
setup.py
xai_components/readme.md
xircuits/handlers/request_submodule.py
xircuits/start_xircuits.py

This PR allows users to pull external libraries and install them automatically using the `xircuits-submodules [xai_library_name]` command. Users can also use `xircuits-submodules --no-install` if they would just like to pull the submodule.
1. Verify that you can pull n install a submodule library using `xircuits-submodule [xai_library_name]`.
2. Verify that you can pull but not install a submodule library using `xircuits-submodule [xai_library_name] --no-install`.
I've also added rabbitmq and mqtt that were missing in the submodules in this PR.

⚡ Pull external XAI library and install cmd

---

.gitmodules

Xircuits - OpenAI component library by @wmeddie. 
Run the examples.

📖  OpenAI Component Library

---

.gitmodules

Xircuits - GPT Agent Toolkit component library by @wmeddie. 
This toolkit provides a comprehensive set of Xircuits components that allow you to experiment with and create Collaborative Large Language Model-based automatons (Agents) in the style of [BabyAGI](https://github.com/yoheinakajima/babyagi) and [Auto-GPT](https://github.com/Torantulino/Auto-GPT). By default, the toolkit comes with BabyAGI agents, but it is designed to be easily customizable with your own prompts.

📖 GPT Agent Toolkit Component Library

---

.gitmodules

Welcome to Xircuits! Thank you for making a pull request. Please ensure that your pull request follows the template.
Add slack connector components library to xai_components
(slack connector components library)[https://github.com/XpressAI/xai-slack]

Add Slack Connector Components Library

---

src/commands/NodeActionCommands.tsx
src/dialog/LiteralInputDialog.tsx
src/helpers/InputSanitizer.tsx
src/tray_library/GeneralComponentLib.tsx

This pull request addresses an issue where users can break the compile process by using incorrect input strings, such as not putting quotations around strings in lists. The code changes introduce a type check to prevent this from happening, ensuring a more robust and reliable compilation process.
The type check has been applied in three key areas:
- When a new literal node is created
- When a literal node is edited
- When users create a new literal node from an 'any' type inPort
We encourage users to test these changes and provide feedback for further improvements.
**1. Check New Literal**
1. Create a new literal node …

🐛 Literal Data Validation to Prevent Compilation Breaks

---

README.md
xai_components/readme.md
xircuits/_version.py

1.8 Release PR. Also updated readmes with the new component libraries and previews.

1.8 Release

---

src/commands/NodeActionCommands.tsx
src/components/xircuitBodyWidget.tsx
src/index.tsx
src/log/LogPlugin.ts
src/ui-components/icons.tsx
src/xircuitFactory.ts
src/xircuitWidget.tsx
style/icons/reload-all.svg

This PR introduces improvements and bug fixes to the reload node feature in Xircuits. Changes include:
- Node reloading now preserves link points.
- Multiple node selections can now be reloaded.
- Added a 'Reload All' button on the toolbar.
- Fixed a bug causing node duplication on reload.
- Resolved an issue where reloading node
s with the same name in succession would break the link.
- Ports that are removed during a reload now disconnect their links.
- Added error popout if component does not exist.
Please conduct the following tests to verify the changes. For easy reload checking, you can modify the color of a component node, eg: @xai_component(color="blue")
**1. Node Reloading Preserves Link Points**
1. Link 2 nodes and modify the connection shape.
2. Reload the node.
3. Verify that …

✨ 🐛 Improved Node Reloading Functionality and Bug Fixes 

---

xai_components/xai_sklearn/readme.md
xai_components/xai_sklearn/requirements.txt
xai_components/xai_sklearn/sklearn_components.py

Component library for scikit learn. Currently only has loading the toy dataset and traintestsplit components, but will add more in the future.
I've noted that sklearn has been used in existing component libraries and examples ie tensorflow keras. Future PRs will update them to use the components from this library.

📖 Scikit Learn Component Library

---

examples/XGBoostClassifier.xircuits
xai_components/xai_xgboost/examples/XGBoostClassifier.xircuits
xai_components/xai_xgboost/readme.md
xai_components/xai_xgboost/requirements.txt
xai_components/xai_xgboost/xgboost_components.py

Component library for [XGBoost](https://github.com/dmlc/xgboost). 
1. Run the XGBoostClassifier example. Verify that it works.

📖 XGBoost Component Library

---

.gitmodules

Xircuits Component Library to interface with Anthropic! Create your Anthropic chatbot application with ease.
**1. Test Workflow**
Run `anthropic_example.xircuits`. Verify that it works.

📖 Anthropic Component Library

---

.gitmodules

A component library to make HuggingFace agents!

📖 HuggingFace Agent Component Library

---

.gitmodules

Xircuits component library to setup a Flask server in Xircuits!

📖  Flask Component Library

---

.gitmodules

A component library that wraps [Thespian](https://github.com/thespianpy/Thespian) so that you can have different actors in your Xircuits diagram that have message queues.
Add if any.

📖 Actor Component Library

---

.gitmodules

Component library to setup your own SQLite database in Xircuits!
None

📖  SQLite Components

---

.gitmodules

Component library to interface with Google Drive and Spreadsheet!
Run the workflows in their respective component library examples directory. Verify that it works.

📖 Google Drive and Spreadsheet Component Library

---

.gitmodules
README.md
xai_components/readme.md

Xircuits component library for Google VertexAI.

📖 Xircuits Google VertexAI Component Library

---

.github/workflows/binder-badge.yaml
README.md
binder/environment.yml
binder/postBuild

This PR adds [Binder](https://mybinder.readthedocs.io/en/latest/index.html) to demo Xircuits. A preview badge is added in the main readme, as well on new pull requests.
1. Test Xircuits Binder preview. Verify that Xircuits runs properly.
Add if any.

✨ Demo Xircuits in Binder

---

.gitmodules

Component library for Xpress AI Agents! This library allows you to define agents that can execute tools which can be defined right in the same Xircuits file.
Currently has support for OpenAI and Google Vertex as LLM backends.

📖 Xircuits AI Agent Library

---

.gitmodules

Xircuits component library for creating an agent accessible with the OpenAI API. Allowing for integration with the Xpress AI Agent Platform.

📖 Xircuits Converse Component Library

---

xai_components/xai_controlflow/branches.py

Adds a flexible boolean expression evaluator for branch components.

Add EvalBooleanExpression

---

xai_components/xai_utils/utils.py

Adds SetDictValue and GetDictValue in Utils.

Add Dict to utils.py

---

.gitmodules

This library provides a set of components that let you interact with the Stability API in Xircuits!

📖 Stability AI Component Library

---

xai_components/xai_controlflow/branches.py
xai_components/xai_utils/utils.py

Adds all my own utility components that I've built over the years, but have neglected to commit upstream.

📖 Additional Utils Components

---

.gitmodules

This repository offers a suite of components designed to integrate the [Google Generative AI library](https://github.com/google/generative-ai-python) into the Xircuits framework. These components facilitate various operations, including content generation, chat sessions, and token counting, leveraging Google's advanced AI models.

📖 Google Gemini Component Library

---

.gitmodules

Adds component library to interface with mongodb.

📖 MongoDB Component Library

---

.gitmodules

Component library to interface with Multion.

📖 Multion Component Library

---

src/commands/NodeActionCommands.tsx
src/components/node/CustomNodeWidget.tsx
src/context-menu/CanvasContextMenu.tsx
src/tray_library/GeneralComponentLib.tsx

This PR allows Argument components to be edited ala Literal nodes.
1. Verify that you can edit argument nodes by double clicking it.
2. Verify that you can edit argument nodes from the right click context menu.
3. Verify that for the edited argument nodes, if they are edited while connected, they should properly reconnect to the original node and there are no dups.

✨ Enable Argument Components to be Edited

---

.gitmodules
xai_components/readme.md

Component Libraries for MS Graph and Gradio.

📖 MS Graph + Gradio Component Library

---

CONTRIBUTING.md
README.md
xai_components/xai_template/HelloTutorial.xircuits
xai_components/xai_template/pyproject.toml

This PR adds HelloTutorial.xircuits which is used in the updated documentation.
https://xircuits.io/docs/main/tutorials/getting-started-with-xircuits
https://xircuits.io/docs/main/tutorials/creating-components-with-xircuits
Ensure that the workflow works as expected and makes sense in the tutorial.

✨ v.13+ HelloTutorial Workflow

---

src/commands/NodeActionCommands.tsx

Attached Literals nodes were previously selectable within the diagram even when part of a bounding box, leading to accidental deletions. This PR fixes that by ensuring attached nodes are not selected when performing the delete action.
Additionally, the logic now ensures attached Literal nodes are deleted if they are the only nodes connected to a component in the library. If the Literal is connected to another node that is not a part of the deletion, it will still be present.
https://github.com/XpressAI/xircuits/pull/340
**1. Test A**  
- Select a node with attached literals and delete it.  
- Verify literals are retained if they have other connections.  
- Ensure only relevant entities are deleted.
**2. Test B**  
- Delete standalone nodes without literals.  
- Confirm correct deletion …

🐛 Fix Delete Logic for Attached Literals

---

.gitmodules
xai_components/readme.md
xircuits/.xircuits/.gitmodules

This PR includes several additions and updates to the Xircuits component libraries:
1. Added new component libraries:
- [Telegram](https://github.com/XpressAI/xai-telegram) - Bot integration components
- [SerpAPI](https://github.com/XpressAI/xai-serpapi) - Search engine results processing
- [SendGrid](https://github.com/XpressAI/xai-sendgrid) - Email service integration
- [GitHub](https://github.com/XpressAI/xai-github) - GitHub automation tools
- [AWS](https://github.com/XpressAI/xai-aws) - Amazon Web Services integration
- [Requests](https://github.com/XpressAI/xai-requests) - HTTP handling components
- [Confluence](https://github.com/XpressAI/xai-confluence) - Atlassian Confluence integration
- [Google Calendar](https://github.com/XpressAI/xai-gcalendar) - Calendar management …

📚 10 New Component Libraries: Telegram, SerpAPI, SendGrid, GitHub, AWS, Requests, Confluence, GCalendar, GTasks, and Twilio

---

xai_components/xai_utils/utils.py

Add components that are useful such as limiting string length and counting characters.
Used in dev env.
Add if any.

Add useful String components to utils

---

src/components/XircuitsBodyWidget.tsx
src/context-menu/TrayContextMenu.tsx
src/index.tsx
src/tray_library/ComponentLibraryConfig.tsx

This PR introduces user notifications and unifies the component library installation into a single shared function
- **Library installation:** pending, success, and error states via `Notification.promise`.
- **Workflow compile:** success & error notifications.
- **Workflow save:** success notification.
- Replaced two separate install paths with a single `handleInstall` that uses `requestAPI`.
- Sidebar **and** Launcher now call the same logic.
- Added `normalizeLibraryName()` so library names are properly formatted for the backend.
- Confirmation dialog now shows the friendly name “Flask” instead of the raw `"xai_flask"`.

✨ Notifications: Install, Save, Compile + Unify Install Logic

---

.github/workflows/run-ui-tests.yml
ui-tests/tests/reload_performance_test.py
ui-tests/tests/xircuits_test_utils.py

This PR adds a new test file `reload_performance_test.py` designed to measure memory performance during the "Reload All Nodes" operation in Xircuits.
Key aspects of the test:
* Measures JS heap usage after each reload (excluding warm-up).
* Measures total DOM node count before and after reload for diagnostics.
* Fails if:
* Heap delta per reload > `MAX_DELTA_MB`
* Net heap growth across all reloads > `MAX_NET_GROWTH_MB`
The thresholds used were established based on multiple local test runs and represent a reasonable performance baseline for the current `LargeCanvas.xircuits` workflow.
To verify that reloading works correctly, one node was edited to remove its `day` output port. The test ensures that after reload, the `day` port reappears, confirming that node updates are successfully …

🧪 Add Performance Test For Memory Usage

---

tests/cli_tests.py

This PR adds a new CLI test to verify that `xircuits run` works correctly when executed **from inside a subdirectory** (such as a library’s `examples` folder).
The test ensures that:
* The workflow compiles and executes successfully.
* No `ModuleNotFoundError` occurs due to `PYTHONPATH` or working directory issues.
* The expected `.py` file is generated and execution finishes without errors.
1. Create a new virtual environment:
```bash
python3 -m venv venv && source venv/bin/activate
pip install -e .
pip install pytest
```
2. Navigate to the `tests` directory:
```bash
cd tests
```
3. Run the new test:
```bash
pytest -v cli_tests.py -k test_33_terminal_run_import_check
```
4. **Expected result:**
* No `ModuleNotFoundError` appears.
* Output contains `Compiled` and `Finished Executing`.
* …

🧪 Add CLI test for `xircuits run` from subdirectory
